### ISSUE TITLE
Ordered return on series distinct

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#103]
As it was noted in PR #101, currently it is not possible to test the `Explorer.Series.distinct()` function because of its unpredictable behaviour when returning the data. It shuffles the series and always returns the result in a different order.
It would be great not having this random behaviour.

Example

```ex
iex(1)> s = [1, 1, 2, 2, 3, 3] |> Explorer.Series.from_list()
#Explorer.Series<
  integer[6]
  [1, 1, 2, 2, 3, 3]
>
iex(2)> s |> Explorer.Series.distinct()
#Explorer.Series<
  integer[3]
  [3, 2, 1]
>
iex(3)> s |> Explorer.Series.distinct()
#Explorer.Series<
  integer[3]
  [2, 3, 1]
>
```

Different results in the same operation.

**Comment by kimjoaoun** [comment]
I see that today we are using Polars' `s_unique` directly. 
I know it might add a little overhead but what about reading the `series`, transforming it in a Polars `DataFrame`, adding a reference column with the right order, remove the duplicates and then apply Polars' [sort](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.sort) to sort the data using the reference column.

**Comment by josevalim** [comment]
Hi @kimjoaoun! Perhaps we should ask the Polars team what they think about it? What are their recommendations?

**Comment by kimjoaoun** [comment]
Hi @josevalim!
I sent a Tweet (not the most formal communication method) to Ritchie and he replied with a possible solution.

https://twitter.com/RitchieVink/status/1485666068018384898

**Comment by josevalim** [comment]
Ah, perfect. So it is really a matter of API design for Explorer. Maybe `distinct` should keep order and `unordered_distinct` for performance? 🤔

**Comment by kimjoaoun** [comment]
@josevalim I think that's great. It is better then having an argument to make that switch, because its way clearer.

**Comment by cigrainger** [comment]
Agreed, that makes sense. I could see going either way, but I think they're sufficiently different to merit different functions.
