### ISSUE TITLE
Explorer.Series.pow does not work when supplied integers as exponent

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#105]
`Explorer.Series.pow` returns an error when the user supplies an integer as exponent. It only works when exponent is a float, and I think because of that all values in the Series are casted to floating point numbers, which is not a desirable behaviour.

When exponent is a integer:

```Ex
iex> s1 = [8, 16, 32] |> Explorer.Series.from_list()
#Explorer.Series<
  integer[3] 
  [8, 16, 32]
>
iex> Explorer.Series.pow(s1, 2)
** (ArgumentError) argument error
    (explorer 0.1.0-dev) Explorer.PolarsBackend.Native.s_pow(shape: (3,)
Series: '' [i64]
[
        8
        16
        32
], 1)
    (explorer 0.1.0-dev) lib/explorer/polars_backend/shared.ex:14: Explorer.PolarsBackend.Shared.apply_native/3
```

When exponent is a float:

```Ex
iex> s1 = [8, 16, 32] |> Explorer.Series.from_list()
iex> Explorer.Series.pow(s1, 2.0)
#Explorer.Series<
  float[3]
  [64.0, 256.0, 1024.0]
>
```

**Comment by cigrainger** [comment]
Good catch. Unfortunately this is because `polars` only takes `f64` for the `pow` method: https://docs.rs/polars/0.18.0/polars/prelude/trait.SeriesTrait.html#method.pow.

I'm sure we could work around it, and at the very least document it!

**Comment by josevalim** [comment]
@kimjoaoun if you could also ping polars folks and ask if they want to support an int version. It could be a good contribution upstream! :heart:

**Comment by kimjoaoun** [comment]
@josevalim I'll ping them!
(se eu estiver sendo chato abrindo vários PRs, por favor, me avise)

**Comment by josevalim** [comment]
Nah, you are being very helpful. Contributions are very welcome! :)

**Comment by kimjoaoun** [comment]
@josevalim It looks like [pow() will be removed](https://github.com/pola-rs/polars/issues/2477), so I think they'll not support an `int` version. I think we would need to do what @ritchie46 suggested and coerce our `integer` to a `float` before sending the information to Rust.

**Comment by ritchie46** [comment]
A bit of context on my rationale to not have this included on the `Series` trait is that this will be compiled for every datatype in polars. 

Doing so for many operations will put a lot of constrain on compile times of polars-core.

The recommended way for a user to apply a numeric operation like `pow`, `sin` `exp` etc. is downcasting the `Series` to the `ChunkedArray` and then calling `apply`

Something like this.
```rust
let s = Series::new("foo", [1i32, 2, 3]);

s.i32()?.apply(|v| v.pow(3)).into_series()
```

Given that Explorer defines bindings to polars, you'd need to pattern match on the `dtype` and downcast to the appropriate type.

**Comment by cigrainger** [comment]
Thanks for the clarification @ritchie46! That makes total sense as a preferred path forward. 

I'm fighting against a Wednesday deadline with work at the minute but could pick this up after. Otherwise @kimjoaoun if you're keen then I can definitely give some guidance and would be happy to review a PR.

**Comment by kimjoaoun** [comment]
@cigrainger I accept the guidance, I'll start working on that. If I have a question I should contact you with a PR comment?

**Comment by cigrainger** [comment]
@kimjoaoun that's probably the best in terms of having a record to point to for others contributing. But you can also get me on the EEF or Elixir slacks (same username) or via email at chris at amplified dot ai.
