### ISSUE TITLE
from_map -> from_series

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#131]
> Somewhat unrelated: another reason to call this function `from_series` is that we could receive any enumerable as a series. This could be beneficial because keywords preserve key ordering but maps do not.

_Originally posted by @josevalim in https://github.com/elixir-nx/explorer/pull/130#discussion_r827678334_

**Comment by josevalim** [comment]
I would also rename `from_list` to `from_rows`. :)

Another thing to consider is if we also want to support `from_series(%{a: some_actual_series, b: another_actual_series})`. If we don't, then perhaps it should be called `from_cols` or `from_columns`.
