### ISSUE TITLE
Should `concat_rows` concat series with integers and floats?

### ISSUE THREAD

**Issue by philss** [elixir-nx/explorer#135]
When creating a new `Series` one can use `Series.from_list/1` that accepts both `integers` and `floats`:

```elixir
iex> Explorer.Series.from_list([1, 2.0, 3])
#Explorer.Series<
  float[3]
  [1.0, 2.0, 3.0]
>
```

But it is not possible to `concat_rows` with data frames that have mixed column types:

```elixir
one = DataFrame.from_map(%{a: [1.0, 2.0, 3.0]})
two = DataFrame.from_map(%{a: [2, 3, 4]})

DataFrame.concat_rows(one, two)

** (ArgumentError) columns and dtypes must be identical for all dataframes
```

Should we have the same behaviour from `Series.from_list/1` for `DataFrame.concat_rows/2`?

This issue was found by @cristineguadelupe :)

**Comment by cigrainger** [comment]
Yes for sure!

**Comment by philss** [comment]
I'm going to try a fix for this.
