### ISSUE TITLE
Possibility to create a series from a list of `nils`

### ISSUE THREAD

**Issue by philss** [elixir-nx/explorer#150]
Should we allow series to be created from a list of `nils`?

```elixir
iex(5)> DF.from_columns(a: [1, 2, 3], b: [nil, nil, nil])
** (ArgumentError) cannot create series "b": cannot make a series from a list of all nils
    (explorer 0.1.0-dev) lib/explorer/polars_backend/data_frame.ex:196: Explorer.PolarsBackend.DataFrame.series_from_list!/2
    (explorer 0.1.0-dev) lib/explorer/polars_backend/data_frame.ex:179: Explorer.PolarsBackend.DataFrame.from_columns_handler/1
```

The current version doesn't allow it - an error sample is displayed above -, so we have to either create the series with one element not being `nil`, or create the dataframe specifying the `dtypes` for our columns. My concern is that some datasets may include columns that are empty and may be hard for the user to spot that.

Both `py-polars` and `nodejs-polars` treats these series of `nils` as a series of `floats` by default.

JS:
```
> pl.Series("foo", [null, undefined])
Proxy [
  shape: (2,)
  Series: 'foo' [f64]
  [
        null
        null
  ],
  { get: [Function: get], set: [Function: set] }
]
```

Python:
```
>>> b = pl.Series("foo", [None, None, None])
>>> b.dtype
<class 'polars.datatypes.Float64'>
```

So what do you think of having the same behavior for Explorer?

PS: this was another issue spotted by @cristineguadelupe

**Comment by cigrainger** [comment]
I'm happy to do that and keep in line with the behaviour of `py-polars` and `nodejs-polars`. Makes sense to me!

**Comment by philss** [comment]
Nice, I will change that tomorrow :)
Thanks!
