### ISSUE TITLE
Use microseconds instead of milliseconds for datetimes

### ISSUE THREAD

**Issue by philss** [elixir-nx/explorer#156]
Since [Polars supports it](https://github.com/pola-rs/polars/pull/2626), we can have more precision when creating datetime series.

**Comment by kimjoaoun** [comment]
It looks like Polars is also supporting nanoseconds!

**Comment by cigrainger** [comment]
Yep, not a bad idea at all! If we can support nanoseconds we should. As we start to expose some more of the time series functionality this will be important.

**Comment by philss** [comment]
OK, I will investigate this. I think we may have a problem with nanoseconds, because it may require a shorter range of dates due to the [limits of `i64`](https://doc.rust-lang.org/std/primitive.i64.html).

There is also the point that we can't represent ns in Elixir, since [`NaiveDateTime`](https://hexdocs.pm/elixir/NaiveDateTime.html) only supports microseconds.

**Comment by cigrainger** [comment]
I think we should match what we can do in elixir. So I think in that case microseconds is the way to go.
