### ISSUE TITLE
What is the best way to pass a custom :datetime format?

### ISSUE THREAD

**Issue by qzg** [elixir-nx/explorer#160]
I'm parsing a file with dates formatted like "11/27/2013 18:55:58.000000" and getting the message:  

> ** (RuntimeError) Polars(ComputeError("Could not find an appropriate format to parse dates, please define a fmt"))
>     (explorer 0.1.0-dev) lib/explorer/data_frame.ex:111: Explorer.DataFrame.read_csv!/2

I'm assuming that date format is just not compatible with whatever standard formats are being tried.  

Is there (or could there be) a way to define a custom format and pass it to Polars?

Thanks!

**Comment by kimjoaoun** [comment]
Hi, qzg!
Could you please provide us with the block of code that you were trying to run?

**Comment by philss** [comment]
Just to complement: we don't have an option for that today. I'm not sure if it's possible to pass down to Polars from the `read_csv/1` operation. But would be a nice feature to have.

For now I think you need to disable the parsing of dates ([`parse_dates` option to false](https://elixir-nx.github.io/explorer/Explorer.DataFrame.html#read_csv/2)), and parse the dates in Elixir. You can use [`Timex`](https://github.com/bitwalker/timex) for parsing the dates.

**Comment by qzg** [comment]
Yeah, ultimately I had to parse the dates into a Polars-friendly format using Elixir and then it imported just fine.  Thank you!
