### ISSUE TITLE
Is there a way to write parquet to s3?

### ISSUE THREAD

**Issue by alantliang** [elixir-nx/explorer#164]
Hi, I want to write a DataFrame directly to s3. How do I convert DF to parquet without writing to file? Thanks!

**Comment by philss** [comment]
Hi @alantliang :wave: 

Right now we don't have a feature for that. But we are considering supporting it. See https://github.com/elixir-nx/explorer/issues/126

If you want to try implementing this, PRs are welcome :)

**Comment by cigrainger** [comment]
Definitely a good idea. Closing as a duplicate of #126.
