### ISSUE TITLE
Best way to iterate over a data frame?

### ISSUE THREAD

**Issue by qzg** [elixir-nx/explorer#165]
Hello-
I've imported 14M rows, filtered and arranged them.  Now I'd like to extract that result for further manipulation outside the scope of what Explorer does.  What's the best way to do this?  I need the output to be more "tabular".

I wrote something simple (below) to turn a data frame into a stream of maps, one "row" at a time, but it is surprisingly slow.  My next attempt to improve performance will be to pre-buffer chunks with DataFrame.slice/3, but I'm not sure that's going to yield much of a gain either.  Before I do that, I'm wondering if there is a "right" way to do this?  I noticed that there is a fold function in Polars but I don't see anything equivalent in Explorer.  

Thanks!

```
  def stream_from_frame(source_frame) do
    Stream.resource(
      fn ->
        limit = DataFrame.n_rows(source_frame)
        starting_index = 0
        {source_frame, limit, starting_index}
      end,
      fn {frame, limit, index} ->
        output_row =
          if index < limit do
            result =
              DataFrame.take(frame, [index])
              |> DataFrame.to_map()
              |> Enum.map(fn {k, [v]} ->
                {k, v}
              end)
              |> Enum.into(%{})

            [result]
          else
            :halt
          end

        {output_row, {frame, limit, index + 1}}
      end,
      fn {_frame, limit, index} -> IO.puts("#{index} rows of #{limit} streamed") end
    )
  end
```

**Comment by jonatanklosko** [comment]
Hey @qzg! We will soon have a [table](https://github.com/dashbitco/table) package that will support this use case. This package has a protocol for reading a data structure as a table, which we will implement for DataFrame. With that we will be able to do `Table.to_rows(df)` to get a stream of maps (or `Table.to_columns(df)`  for traversing individual series) :)

**Comment by qzg** [comment]
Thank you!  So...  _how soon_...?  :-)

**Comment by jonatanklosko** [comment]
For a technical reason we need to wait before publishing the package, but hopefully in a week or two. I have a PR for Explorer integration ready, will submit as soon as we publish the package :)

**Comment by jonatanklosko** [comment]
FTR as of #185 there is `DataFrame.to_rows` and `DataFrame.to_columns` that you can use directly!
