### ISSUE TITLE
Option to manually supply types to `from_rows`

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-nx/explorer#175]
I'm currently using explorer to convert a database table to parquet files, but sometimes batches only hold null values for a column, so type inference fails: `Could not infer row types, because of the null values`

**Comment by cigrainger** [comment]
Good idea! I'll look into this. @jonatanklosko is this handled in `table`?

**Comment by jonatanklosko** [comment]
@cigrainger `table` doesn't track types, it only allows to read the values, either row-by-row or column-by-column. Note that we could always read tabular data as columns with `Table.to_columns` and effectively use `from_columns` with its type inference. 

However, the underlying `Table.Reader` protocol works such that, the given data structure describes either by-row or by-columns access, then `Table.to_columns` does the conversion if necessary. It may be that we can implement `DataFrame.new` to use the `Table.Reader` protocol directly and picks the most efficient way to load the data. That's something I plan to look into!

**Comment by cigrainger** [comment]
Thanks @jonatanklosko!

**Comment by cigrainger** [comment]
I think we should be able to do this with [`DataFrame::from_rows_and_schema`](https://docs.rs/polars/0.21.0/polars/frame/struct.DataFrame.html#method.from_rows_and_schema). I'll take a look :).

**Comment by LostKobrakai** [comment]
@cigrainger seems like this might have been closed accidentally. I don't see how `DataFrame.new` would allow someone to manually supply types rather than using inference.

**Comment by josevalim** [comment]
I will open up a new issue so we provide a consistent API for all of these.
