### ISSUE TITLE
Make Nx an optional dependency

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#177]
The `keyword!` function is now part of Elixir as `Keyword.validate!`.

For the tensor operations (to_tensor and from_tensor), we can add `@compile {:no_warn_undefined, Nx}`.

**Comment by cigrainger** [comment]
I've been meaning to go back and use `Keyword.validate!` for aaaages. Thanks for the reminder. I didn't realise we could use optional deps at compile time! That's really cool.

**Comment by cigrainger** [comment]
Is this still a good idea if we intend to implement the `Nx.Container` protocol?

**Comment by josevalim** [comment]
We can wrap the Nx.Container implementation in a `Code.ensure_loaded?(Nx)` block too. :)

**Comment by josevalim** [comment]
As long as we list it as an optional dependency, if someone adds Nx as a dependency, Mix will figure things out and guarantee the proper compilation order!
