### ISSUE TITLE
Mirror names with Nx API

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#189]
There are some Series APIs that are slightly different to Nx:

* `cum_min` and friends are called `cumulative_min` in Nx
* `rolling_min` and friends are called `window_min` in Nx

Should we aim to unify those? I am open to changing Nx if desired too or staying different. :)

**Comment by josevalim** [comment]
The APIs are similar but they accept different options. There is no reverse in `cummulative_min` in Nx. I assume this option exists in Polars for efficiency purposes? In any case, we could add one to Nx no problem. In `window_min`, the window is a shape because it can be multidimensional, which in a Series it is just a number. It is a minor and understandable difference. I will leave it up to you to decide if it is worth it. :) But if you do, here is what we should do:

1. Explorer: Make reverse an option in cum_min
2. Explorer: Rename cum_ to cumulative_
3. Explorer: Rename rolling_ to window_
4. Nx: Add :reverse as an option to cumulative functions

**Comment by cigrainger** [comment]
Honestly I can't think of a reason to have `reverse` as an option at all other than that it's possible :). Fairly straightforward either way.

**Comment by josevalim** [comment]
@cigrainger given all operations on series are eager, i assume it is for performance then!
