### ISSUE TITLE
Provide complete range of IO operations

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#190]
Each IO operation must have 8 functions: `dump`, `load`, `from` and `to` as well as the `!` version of them. This is an issue to add the missing APIs. We can break it apart per IO type:

  * [ ] CSV
  * [ ] Parquet
  * [ ] Arrow
  * [ ] Streaming Arrow
  * [ ] NDJSON

Although I recommend tackling #187 before this one!

**Comment by josevalim** [comment]
We should probably normalize the Rust APIs well.

**Comment by josevalim** [comment]
All of the dump functions should return the contents that we would have found in the file if we used to_format + File.read. So the idea is to skip the writing to disk, and already have the contents in memory.

**Comment by kimjoaoun** [comment]
Working on this one.
This issue is my current priority.

**Comment by MarceColl** [comment]
Is there any update on this?

**Comment by kimjoaoun** [comment]
Yes @MarceColl. I'm planning to send the PR that will close this issue later this week.

**Comment by MarceColl** [comment]
Perfect, thanks @kimjoaoun that's awesome :)

**Comment by isaacsanders** [comment]
Will this read from S3?
