### ISSUE TITLE
Add lazy backend

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#195]
- [x] Add `Explorer.PolarsBackend.LazyDataFrame` backed by `ExLazyFrame`
- [x] Add `lazy/0` (returns the lazy version of the current backend - noop if already lazy)
- [x] Add `to_lazy/1` (returns the lazy version of the current dataframe - noop if already lazy)
- [x] Add `collect/1` (returns an eager version of the current dataframe - noop if already eager)
- [x] Raise for unsupported functions
- [x] Implement sufficient functions to inspect

**Comment by josevalim** [comment]
> Add Explorer.Backend.LazyDataFrame with one or two functions initially

I don't think we should have a new backend specification. It is the same backend specification which will raise if the function is not supported for lazy backends. So our initial implementation can actually do the same trick as we do in the template backend in Nx, and raise for most functions:

https://github.com/elixir-nx/nx/blob/main/nx/lib/nx/template_backend.ex#L18-L29

We should also add three new functions: `lazy/0` (returns the lazy version of the current backend - noop if already lazy), `to_lazy/1` (returns the lazy version of the current dataframe - noop if already lazy)  and `collect/1` (returns an eager version of the current dataframe - noop if already eager).

**Comment by cigrainger** [comment]
Ahhhh that makes sense. I knew I was missing something. Got it now. 👍

**Comment by cigrainger** [comment]
This is nearly done but I'm running into some trouble with `Inspect`. It needs to be different for lazy and eager. I can handle that by handing off to different inspect functions in `defimpl Inspect, for: Explorer.DataFrame` with:

```elixir
cond do
  impl!(df) == Backend.get().DataFrame -> inspect_df(df, opts)
  impl!(df) == Backend.get().LazyDataFrame -> inspect_ldf(df, opts)
end
```

Is that reasonable?

Then I need to come up with how I want inspect to look. One option is just to keep it the same but to add a `lazy?` flag and not show rows. So that would look like:

```
      #Explorer.DataFrame<
        [columns: 5, lazy?: true]
        sepal_length float [5.1, 4.9, 4.7, 4.6, 5.0, ...]
        sepal_width float [3.5, 3.0, 3.2, 3.1, 3.6, ...]
        petal_length float [1.4, 1.4, 1.3, 1.5, 1.4, ...]
        petal_width float [0.2, 0.2, 0.2, 0.2, 0.2, ...]
        species string ["Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa", ...]
      >
```

That's in keeping with the current `groups` behaviour, which doesn't show if there are no groups. If we always wanted to show `lazy?: false` when it's false, then we'd need to make that consistent for `groups` too. So then it would be more like:

```
[rows: NA, columns: 5, groups: [], lazy?: true]
```

**Comment by philss** [comment]
> Is that reasonable?

I think so. In the future we may need to delegate some of the inspection to the backends (I'm thinking of some specific backends, like a SQL one).

> Then I need to come up with how I want inspect to look. One option is just to keep it the same but to add a lazy? flag and not show rows. So that would look like:

It looks good to me! An alternative could be to show the name of the backend, and don't show the rows. Something like this:

```
#Explorer.DataFrame<
  [columns: 5, backend: :polars_lazy]
  sepal_length float [5.1, 4.9, 4.7, 4.6, 5.0, ...]
  sepal_width float [3.5, 3.0, 3.2, 3.1, 3.6, ...]
  petal_length float [1.4, 1.4, 1.3, 1.5, 1.4, ...]
  petal_width float [0.2, 0.2, 0.2, 0.2, 0.2, ...]
  species string ["Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa", "Iris-setosa", ...]
>
```

WDYT?

**Comment by cigrainger** [comment]
@philss see https://github.com/elixir-nx/explorer/pull/222 🙏
