### ISSUE TITLE
Do not add special meaning to empty lists

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#205]
Some APIs make empty lists behave specially. For example, like selecting all columns. @philss tackled many of those in #201 but some still remain:

  * [ ] `distinct` raises on empty list, instead it should return the data frame as is

  * [ ] `rename_with` raises on empty list, instead it should return the data frame as is

  * [ ] `pivot_wider` makes empty lists be all columns, but the default should be nil instead. However, I am not sure if we can support empty lists here. So we may need to raise.

**Comment by kimjoaoun** [comment]
About the `pivot_wider` case: I think we should `raise`. Pivoting is a big operation that completely changes the way the data is being structured, its best to avoid an unintended result.
But yes, sometimes using all columns is something that we might want to do, so I suggest having `:everything` atom as a fast way to pass all columns to pivot_wider.

**Comment by cigrainger** [comment]
Hmmm... in [`tidyr::pivot_wider()`](https://tidyr.tidyverse.org/reference/pivot_wider.html) a `NULL` for `id_cols` defaults to _everything but `names_from` and `values_from`_ and I think that's the right way to go.
