### ISSUE TITLE
Add dtypes support on DataFrame.new/2

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#219]
#218 already introduces an API to validate and normalize dtypes. The idea is to support a similar style of options during `new/2`.

Continues #175.

**Comment by kimjoaoun** [comment]
Can I get this one?

**Comment by josevalim** [comment]
Yes pls!

**Comment by nallwhy** [comment]
Is only integer -> float normalization possible?

**Comment by josevalim** [comment]
I think so... so maybe it is not worth it? We can normalize it after the fact. I will close this for now. :)
