### ISSUE TITLE
Add tabular print method

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#22]
Useful influences:
https://github.com/alexhallam/tv
https://pillar.r-lib.org/dev/index.html

**Comment by kenny-evitt** [comment]
I like this library for 'tabular printing' of, e.g. lists of maps, structs, `Ecto` schema-structs, etc.:

- [codedge-llc/scribe: Pretty print tables of Elixir structs and maps](https://github.com/codedge-llc/scribe)

**Comment by josevalim** [comment]
Axon also uses https://github.com/djm/table_rex.

**Comment by kimjoaoun** [comment]
I've been doing some experiments with `table_rex` and achieved this result are you looking for something similar to this?

![last_screenshot](https://user-images.githubusercontent.com/43274384/152263260-1ed43cdc-0114-429d-ad9e-2ebbee230c8f.png)

**Comment by cigrainger** [comment]
Yes! That's fantastic.

**Comment by kimjoaoun** [comment]
Hehe, ok. As you can see, the code need some fixes (types are in the wrong order), I'll work on that.
But another question, where would we put this function? In which file?

**Comment by cigrainger** [comment]
It'd go [here](https://github.com/elixir-nx/explorer/blob/main/lib/explorer/inspect.ex). I'd like to keep the current version as `DataFrame.glimpse(df)` but honestly the code is a hot mess.
