### ISSUE TITLE
Function that finds the first non-missing element in a vector

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#226]
## Introduction

I would be good having in the module `Explorer.Series` a function similar to dplyr's [coalesce](https://dplyr.tidyverse.org/reference/coalesce.html) or postgreSQL's [coalesce](https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL).
In Pandas there's a function called [DataFrame.combine_first](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.combine_first.html) that do something similar, but I'm not sure if it achieves the same results as the ones described above.

What coalesce's do is:
Having a pair of vectors of the same length, merge them, keeping the first value of each side of the pair that is not a `:nil`

## Examples

```elixir
iex> s1 = Explorer.Series.from_list([1, 2, 3, nil])
iex> s2 = Explorer.Series.from_list[nil, nil, nil, 4])

iex> Explorer.Series.coalesce(s1, s2)
#Explorer.Series<
  integer[3]
  [1, 2, 3, 4]
>
```

**Comment by cigrainger** [comment]
I think we can use [`Series::zip_with`](https://docs.rs/polars/latest/polars/series/struct.Series.html#method.zip_with). Not what I think of when I think of `zip_with` -- more like vectorised `if_else` in `dplyr`. So given `s1` and `s2` it would be: `s1.zip_with(s1.is_null(), s2)`.

**Comment by kimjoaoun** [comment]
Hmm, that looks like a fun one, but I'm currently busy doing #190.
What do you think of tagging this as a "Good First Issue"? It doesn't look like a hard one -- and I can be available to help, if needed.
