### ISSUE TITLE
hstack/bind_cols functionality

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#228]
We have `concat_rows` for vertical stacking/`bind_rows`. We should also have `concat_columns` for
horizontal stacking/[`bind_cols`](https://dplyr.tidyverse.org/reference/bind.html).

This should be pretty straightforward as `polars` has [`DataFrame::hstack`](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.hstack).

**Comment by kimjoaoun** [comment]
For some reason I thought we already had this functionality.

**Comment by cigrainger** [comment]
We had it in rust but not exposed, and removed it from Rust when cleaning out unused functions.
