### ISSUE TITLE
Improve `summarise` API

### ISSUE THREAD

**Issue by cigrainger** [elixir-nx/explorer#230]
I'm not a fan of the `agg` approach a la `pandas` and much prefer [`dplyr`'s `summarise`](https://dplyr.tidyverse.org/reference/summarise.html). Lazy polars can get us there, such that the `summarise` API and `mutate` API can be almost identical.

Also probably need to add aliases for `-ise` to `-ize` for American spelling.

**Comment by josevalim** [comment]
Closing this in favor of #223. :)
