### ISSUE TITLE
n_columns and shape return different values for grouped dataframes

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#231]

**Comment by cigrainger** [comment]
`n_columns` shouldn't return a different value. That's a bug. `shape` might, but probably shouldn't. In fact... this is definitely a bug. But we should figure out a way to do something similar to `dplyr::n()`, which permits per-group row counts. This is a really common use case (so much you can use `dplyr::count()` which is super useful).

**Comment by josevalim** [comment]
Closing in favor of #245.
