### ISSUE TITLE
Change series inspect implementation

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#233]
Series also have backends and we need to include them. One option is to mirror dataframe. WDYT?

```
#Explorer.Series<
  Polars[1024]
  integer [1, 2, 3, 4, 5, 6, 7, 8, ....]
>
```

Thoughts @cigrainger?

**Comment by cigrainger** [comment]
Oh I think that's very nice. Mirroring dataframe makes sense to me.

**Comment by nallwhy** [comment]
@josevalim Can I get this one?

**Comment by josevalim** [comment]
Yes! You are doing awesome work, feel free to pick up anything :)
