### ISSUE TITLE
Align pivot_longer with dplyr 

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#241]
In dplyr, the `cols` argument to `pivot_longer` is actually the columns we would like to pivot. I find that API a bit more intuitive. Should we change our implementation to align with theirs? :)

**Comment by philss** [comment]
For what I could understand, the current API treats the columns argument as "columns to keep". This seems to be something that is not accept by [`dplyr's` API](https://tidyr.tidyverse.org/reference/pivot_longer.html). Do you think we can add an option to keep supporting this feature, or should we drop it?

If so, maybe `columns_to_keep`?

The API would look like `pivot_longer(df, columns_to_pivot, opts)` where opts accepts `:names_to`, `:values_to` and `:columns_to_keep` (with default to []).

**Comment by philss** [comment]
I'm going to assume we are going to keep it. It's easier to remove if we decide otherwise :)
I will send a PR later today.

**Comment by josevalim** [comment]
Sounds good to me. I would simply call it `:keep` though. Both `columns_to_pivot` and `keep` accept a function too.

**Comment by cigrainger** [comment]
@josevalim now I'm a bit confused. The current API for `Explorer.DataFrame.pivot_longer/3` matches the tidyr API. That is: the second arg is the 'columns to pivot'. `values_from` is _additional_ to the tidyr API and is a convenience function to select (because we don't have tidy select).
