### ISSUE TITLE
Accept `limit:` keyword on DataFrame.table instead of num_rows integer

### ISSUE THREAD

**Issue by dkuku** [elixir-nx/explorer#243]
Currently by default explorer displays 5 lines and when I wan't to display the whole data frame I need to know the shape.
`Explorer.DataFrame.table(iris_df, 150)`
I think it would be better to accept `limit` keyword similar to `IO.inspect` does - by default it shows just part of the data - same as explorer and if you wan't more you can pass `limit: :infinity` or `limit: 150`.
I can make a pr

**Comment by josevalim** [comment]
Sounds good to me, I think moving to a keyword will be "safer" long term if we want to add more options. Can you please try a PR for us to see how it looks like?

**Comment by dkuku** [comment]
sure-will do that

**Comment by cigrainger** [comment]
Closed by #244 ❤️
