### ISSUE TITLE
Revisit operations when grouped

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#245]
Ideally we will have a separate test file for testing how each of them works when grouped, removing all of .group calls from data_frame_test.exs.

### Group handling

* [x] group_by
* [x] ungroup
* [x] summarize

### Behaves different under group:

* [x] arrange (in dplyr the group behaviour is opt-in)
* [x] arrange_with
* [x] collect (document that collecting a grouped data frame should return a grouped data frame)
* [x] distinct
* [x] head
* [x] mutate
* [x] mutate_with
* [x] rename (rename grouped columns)
* [x] rename_with (rename grouped columns)
* [x] sample (sample 5 of each group)
* [x] select (raise if dropping grouped columns) => should raise? today is no-op if grouped is passed
* [x] slice
* [x] tail
* [x] ~take~ (renamed to slice)
* [x] filter_with

### No changes under group

* [x] ~filter~ (is now only `filter_with`)
* [x] n_columns
* [x] n_rows
* [x] pull
* [x] shape
* [x] to_* (a small test for some of them is enough)

### To discuss

* [x] pivot_longer
* [x] pitot_wider
* [x] dummies
* [x] concat_rows/concat_columns (what if one side has the grouping and the other does not?)
* [x] join (what if one side has the grouping and the other does not?)

**Comment by philss** [comment]
I think `slice/2` won't work with ranges for a grouped dataframe, because we can't know the size of each group beforehand. I think we could only support `slice/2` with row indices. WDYT?

**Comment by josevalim** [comment]
@philss ah... in this case, maybe we should pass the range all the way down to Rust? Or at least the start, stop, and stride. It is a bit annoying because we would need to implement the normalization in rust but it should be relatively straight-forward.

**Comment by philss** [comment]
@josevalim yeah, makes sense. :+1: 
I'm going to try that. My only concern is that Rust ranges don't accept steps. But I can validate that in the backend.

**Comment by philss** [comment]
I'm investigating the rest of the operations (the ones from "To discuss" section) and I will follow the behaviour we see in dplyr, if that is OK for you.

For `pivot_longer` and `pivot_wider` the groups are kept if they are not used in the pivoting operation. For example, if we have a group that is used as a column to `pivot_longer`, that group is not going to appear in the resultant dataframe. I have to fix our code to follow this behaviour.

**Comment by philss** [comment]
The `join` operations described in https://dplyr.tidyverse.org/articles/two-table.html don't specify what happens with groups, but I found that the groups are kept if they are in the left-hand side of the operation.

So, for example, if we have two dataframes:

```elixir
df1 = Explorer.DataFrame.new(x: [1, 2], y: [2, 1])

df2 = Explorer.DataFrame.new(x: [3, 1], a: [10, 10], b: ["a", "a"])
Explorer.DataFrame.inner_join(df1, df2)
```

If we add a group in `df1`, this group is going to be present in the resultant dataframe.
Buf if we add a group in the `df2`, it is not going to be in the joined DF.

Do you think this behaviour is fine?

**Comment by josevalim** [comment]
For left join it makes sense to keep one side but not the other. Then inner_join makes sense to mirror left_join. So I agree with this behaviour.

**Comment by philss** [comment]
For `concat_rows`, I could only find the `union/union_all` operations that are similar in dplyr: https://dplyr.tidyverse.org/reference/setops.html

They will keep only the groups of the first dataframe (or the left-hand side df), and ignore the rest.
I think this is fine, and I'm going to document/test that.

**Comment by philss** [comment]
Closing this, since all the functions are fixed and documented. :tada: 
If we have more that are not in this list, we should create individual issues. :)
