### ISSUE TITLE
Publish explorer to crates.io

### ISSUE THREAD

**Issue by joshuataylor** [elixir-nx/explorer#246]
Hi

I've built an extension for explorer that transforms the Snowflake streaming arrow files to Explorer.

The problem with SF is that it requires a little bit of data manipulation to convert to timestamps and other funness, so a library is required for this.

I want to include explorer in my project, so I can use the datatypes.

**Comment by cigrainger** [comment]
I don't see any problem with this. Let me see what I can do. :) Ideally releases should be synced and we're not far off 0.2.0 so I may wait for that, but I suppose I can publish a prerelease.

**Comment by cigrainger** [comment]
Also super cool you've built an extension for Explorer! I'm excited to check it out. :)

**Comment by josevalim** [comment]
Hi @joshuataylor!

My concern with pushing Explorer to Cargo is that we will load the binary code multiple times.

Can you share the extensions? Maybe they belong to Explorer? Or alternatively we can find out a mechanism to include them dynamically? Or are they compile time dependencies?

**Comment by cigrainger** [comment]
Also @joshuataylor you can always use a git dependency!

**Comment by joshuataylor** [comment]
Sure, so a few problems:

1/ Including via git is great, but I can't do that with a cdylib, as "rlib" will need to be added to explorers' `Cargo.toml`. We /could/ split the types if this is going to be a problem.

2/ You can see the code here: 
https://github.com/joshuataylor/explorer_snowflake/blob/main/native/explorer_snowflake/src/lib.rs

And here:

https://github.com/joshuataylor/explorer_snowflake/blob/main/native/explorer_snowflake/src/snowflake_polars.rs

I want to split `snowflake_polars.rs` into another repository so this can be used from Polars directly as well, then we just rely on `polars_snowflake` from `explorer_snowflake` :).

**Comment by josevalim** [comment]
@joshuataylor am I correct to say that the functionality that we are missing is the handling of `ArrowDataType::Struct(_f)`?

If so, I wonder if any of those two options are possible:

1. Have a way to register custom parsers in Explorer at runtime. So you would call something like `Explorer.PolarsBackend.register_logical_type("TIMESTAMP_NTZ", Snowflake.Explorer.timestamp_ntz_address())`. The callback will be invoked with the `ArrowDataType::Struct(_f)`.

2. If that doesn't work or it is too tricky, we can return the logical type and its underlying binary to Elixir, Elixir then does the logical type, and then calls back a function (which may be another Rustler NIF for parsing). This should also be relatively cheap, the only cost is leaving the NIF and re-entering it once per series.

**Comment by joshuataylor** [comment]
I like your idea, but we'll need to test it with different datasizes to see how it performs. Snowflake sends back chunks that are around 100kb to 50mb when uncompressed. I found that doing 100-200k conversions for Timestamps was slow to process, especially if you return the struct type between Rustler and Elixir.

And the way they do floats sometimes: https://github.com/joshuataylor/explorer_snowflake/blob/main/native/explorer_snowflake/src/snowflake_polars.rs#L63

I need to test the timestamps with the "TIMESTAMP_NTZ"/"TIMESTAMP_LTZ"/"TIMESTAMP_TZ" to double check the timezones, as they pass back the timezone info.

For example in the JSON implementation in `req_snowflake`, here is how we do it with timestamp_tz: (the convert function just looks up the timezone, similar to how to gosnowflake implementation does things):

```elixir
  defp decode_json_column(%{"type" => "timestamp_tz"}, value) do
    # It's a timestamp nano with an offset in a space.
    # Looks like "1588969216076000000 1440"
    [timestamp_string, offset_string] = String.split(value, " ")
    offset = String.to_integer(offset_string)

    timestamp =
      timestamp_string
      |> String.replace(".", "")
      |> String.to_integer()

    # What we now do is take the offset, which should be an integer and minus 1440 from it.
    offset = offset - 1440

    # We now need to lookup all timezones with this offset, which will then be the actual timezone
    # Offset is in minutes. If it is 0, we'll assume UTC.
    timezone = ReqSnowflake.Timezone.convert(offset)

    ReqSnowflake.Timezone.unix_timestamp(timestamp, timezone)
  end
```

**Comment by joshuataylor** [comment]
So we'll need to create another crate, as

1/ Using `cdylib` is great for NIFs, but bad if you want to rely on it, as it strips all Rust related information.
2/ Changing to dylib throws an error that `rustler::init` is already defined in explorer.

**Comment by josevalim** [comment]
@joshuataylor would the Elixir approach I mentioned above not be enough? We find a way of transferring the underlying array buffer between runtimes, using zero copy, through Elixir.

This is what we are exploring for Nx too. For example, a library like StbImage can allocate an image in memory, but another completely independent library may want to use it without copying, so we share it.

**Comment by joshuataylor** [comment]
I'd be happy with that.

I'll leave `explorer_snowflake` for now, and return to it once we have this. We could even use it as the initial test integration?

I'll make snowflake_arrow rely directly on Polars, once this in I'll change it over to explorer.

**Comment by josevalim** [comment]
@joshuataylor could you join the Erlang Ecosystem Foundation Slack? You can create an account for free and then click the sidebar link: https://erlef.org/wg/machine-learning

Or shoot me an email. I think jumping into a call will be quicker. :)

**Comment by josevalim** [comment]
Oh, before I forget, I don't think you need to migrate snowflake_arrow to Polars either. The idea is to share arrow buffers so just arrow is fine.

**Comment by josevalim** [comment]
Closing this, as we want to explore those extensions as built-ins to Explorer. :)
