### ISSUE TITLE
Mutable dataframes

### ISSUE THREAD

**Issue by joshuataylor** [elixir-nx/explorer#249]
When working with polars, it's sometimes handy to have mutable dataframes.

This is because you want to change the dataframe without creating a new one, or doing lots of operations, which can save memory, CPU & time.

For example, if I wanted to read many Arrow files into one dataframe, I could do something like this with polars:

1/ Create a dataframe as mutable:
```rust
let mut df = mutDataFrame::new(my_series); 
```

2/ Use [vstack_mut](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.vstack_mut) to add them to the existing df.
```
    for file in files {
        let some_df = ...;
        df.vstack_mut(&some_df).unwrap();
    }
```

Doing it via vstack_mut is much faster then doing it via vstack, this takes ~5s on my PC for vstack vs vstack_mut which takes 950ms.

So to do this in Rustler, we would need to have a `Mutex` ResourceArc. What are the thoughts around this? Bad idea? Lock it behind a very stern warning about shooting yourself in the foot?

From my experiments, here is what I did (excuse the code, was just a test to see how it worked):

1/ Do
```
pub struct SnowflakeArrowDataframeResource(pub Mutex<DataFrame>);
pub type SnowflakeArrowDataframeArc = ResourceArc<SnowflakeArrowDataframeResource>;

fn load(env: Env, _info: Term) -> bool {
    rustler::resource!(SnowflakeArrowDataframeResource, env);
    true
}
```

Then I have the following:
```
#[rustler::nif(schedule = "DirtyIo")]
pub fn convert_snowflake_arrow_stream_to_df(
    arrow_stream_data: Binary,
) -> (Atom, SnowflakeArrowDataframeArc) {
    let resource = ResourceArc::new(SnowflakeArrowDataframeResource(Mutex::new(
        snowflake_arrow_ipc_streaming_binary_to_dataframe(&mut arrow_stream_data.as_ref()).unwrap(),
    )));

    (atoms::ok(), resource)
}

#[rustler::nif(schedule = "DirtyIo")]
pub fn append_snowflake_arrow_stream_to_df(
    resource: ResourceArc<SnowflakeArrowDataframeResource>,
    arrow_stream_data: Binary,
) -> Atom {
    let mut df1 = match resource.0.try_lock() {
        Err(_) => return atoms::lock_fail(),
        Ok(guard) => guard,
    };

    let df =
        snowflake_arrow_ipc_streaming_binary_to_dataframe(&mut arrow_stream_data.as_ref()).unwrap();

    match df1.vstack_mut(&df) {
        Ok(_) => atoms::ok(),
        Err(_x) => atoms::todo_error(),
    }
}
```

**Comment by cigrainger** [comment]
Good point! I think we could split the difference and:
1. Pass a list of dataframes for stacking
2. Clone the first
3. Use `fold()` with `vstack_mut()`.

**Comment by joshuataylor** [comment]
Oh yeah, that would be great, if we could do that internally it'll speed things up massively.

**Comment by josevalim** [comment]
Coincidentally I was talking about this to @philss yesterday, for us to move some of the operations to Rustler to generate less garbage. I didn’t realize we could make them mutable too. /cc @philss

**Comment by joshuataylor** [comment]
I've found that translating data back from Rustler is very expensive in terms of memory/GC, so I've tried to do as much as I can on the Rust side before moving back to Elixir. I've been testing on wide datasets (300 columns, 500k rows) and will keep ramping up the testing as I figure out how to tame the GC, as once the data is actually IN Erlang/Elixir it's fine.

**Comment by josevalim** [comment]
@joshuataylor which particular part is expensive? I would imagine that we keep references to the underlying arrow binary most times, unless you do Series.to_list or DataFrame.to_columns or similar. Or do you mean on immutable operations like above?

---

Also note we are working on lazy backends. The idea is that you can do:

    dataframe
    |> DF.to_lazy()
    |> ...
    |> DF.collect()

And all operations will now happen once (we can make them mutable internally too).

---

In any case, those benchmarks are extremely helpful, so please keep them coming. I am just trying to understand exactly where the root issue is!

**Comment by joshuataylor** [comment]
Yeah, the `DataFrame.to_columns` part.

Awesome about the lazy backends, that would be amazing as we could build all the parts of the dataframe we need, then collect it. Polars is incredibly powerful that way.

**Comment by josevalim** [comment]
@joshuataylor for Snowflake (and req_snowflake in particular), I would return the data in Explorer. The user can request it to become Elixir data on their own if/when they need it.

I have also opened #251 to tackle the mutable stuff. We can close this perhaps?

**Comment by joshuataylor** [comment]
That makes sense wrt Snowflake :).
