### ISSUE TITLE
Add `df_read_binary_*` to read a Binary

### ISSUE THREAD

**Issue by joshuataylor** [elixir-nx/explorer#264]
So there are these functions for reading files of various types:
```
#[rustler::nif(schedule = "DirtyIo")]
pub fn df_read_parquet(filename: &str) -> Result<ExDataFrame, ExplorerError> {
    let f = File::open(filename)?;
    let df = ParquetReader::new(f).finish()?;
    Ok(ExDataFrame::new(df))
}
```
This is just for files. We should be able to pass a [Rustler binary](https://docs.rs/rustler/latest/rustler/types/binary/index.html), so you could pass a binary straight from Elixir. We **could** rename to df_read_parquet_file, but this would break backwards compatibility.

My proposal is to add `df_read_*_binary` functions to read Binaries:
```
#[rustler::nif(schedule = "DirtyIo")]
pub fn df_read_xxx_binary(
    binary: Binary,
    columns: Option<Vec<String>>
) -> Result<ExDataFrame, ExplorerError> {
    let df = IpcReader::new(binary.as_ref())
        .with_columns(columns)
        .with_projection(projection)
        .finish()?;
    Ok(ExDataFrame::new(df))
}
```

Thoughts?

**Comment by josevalim** [comment]
Check #190. :)
