### ISSUE TITLE
Add collect_rows/collect_columns operations

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#271]
We need to provide a mechanism for reading data stored across multiple files. Currently, we can support this by reading N files and then performing a `concat_rows`, but that means at a certain moment we will have twice the size of the dataset in memory, which may be too large.

I propose we add `collect_rows` as a function which returns an Elixir [Collectable](https://hexdocs.pm/elixir/Collectable.html).  This means, if we want to read multiple files in a directory, we can do this:

```elixir
dir
|> Path.join("**/*.csv")
|> Path.wildcard()
|> Stream.map(&DataFrame.read_csv/1)
|> Enum.into(DataFrame.collect_rows())
```

Or if you like a comprehension:

```elixir
for path <- dir |> Path.join("**/*.csv") |> Path.wildcard(),
    do: DataFrame.read_csv(path),
    into: DataFrame.collect_rows()
```

This means we will only keep the size of N+1 dataframes in memory.

We can also do cool stuff like reading multiple files from S3 while keeping an upper bound on concurrency:

```elixir
1..16
|> Task.async_stream(fn index ->
  Req.get!("s3://path-to-bucket/#{index}.parquet").body
end)
|> Stream.map(&DataFrame.read_parquet/1)
|> Enum.into(DataFrame.collect_rows())
```

We could even support this alongside lazy frames to implement functionality requested in #128:

```elixir
dir
|> Path.join("**/*.csv")
|> Path.wildcard()
|> Stream.map(fn file ->
  DataFrame.lazy().read_csv(file) |> add_partitions_from_file(file)
end)
|> Enum.into(DataFrame.collect_rows())
```

Open questions:

1. What do we return if you pipe an empty list into collect_rows? Do we raise? An empty data frame?

2. `collect_rows` has some ambiguity with the existing `collect` function, as we are mixing the collectable meaning in Elixir with the one in dplyr. But it feels they are related enough?

/cc @joshuataylor

**Comment by josevalim** [comment]
Another worthy mention is that we can likely reduce copying altogether if Polars has an API for reading CSV/Parquet/IPC/etc into an existing dataframe but I don't think such functionality exists. Does it?

**Comment by cigrainger** [comment]
@josevalim I don't think polars has anything directly for that but there are lazy readers and you could use a lazy reader and a lazy vstack to achieve the same. Either way I love this idea.

**Comment by cigrainger** [comment]
Re: the open questions:

1. I think an empty DF as I don't see much value in raising there. But I could see it being annoying. I think it's a minor footgun potentially but not a terrible one.
2. I do have to say my immediate thought was that this would be about converting to Elixir data, e.g. replacing to_rows and to_columns. I almost want to call it accumulate or something like that. But also.... the ambiguity isn't terrible and you're right they are somewhat related.

**Comment by joshuataylor** [comment]
1. I really like this (as mentioned above)
2. Lazy frames has the option to scan a directory, eager is one at a time, then use vstack or vstack_mut to put the new df on the old one or vica verca. Not sure what the memory usage would be like not doing it in a single `vstack_mut`, but it's significantly faster appending a single mutable dataframe.
2a. It might be worthwhile having a look at the Python implementation of Polars and how to explain  https://pola-rs.github.io/polars-book/user-guide/howcani/io/csv.html
3. Instead of building dfs that way, we should use [CsvReader::from_path](https://docs.rs/polars/latest/polars/prelude/struct.CsvReader.html#method.from_path)
```
impl<'a> CsvReader<'a, File> {
    /// This is the recommended way to create a csv reader as this allows for fastest parsing.
    pub fn from_path<P: Into<PathBuf>>(path: P) -> Result<Self> {
        let path = resolve_homedir(&path.into());
        let f = std::fs::File::open(&path)?;
        Ok(Self::new(f).with_path(Some(path)))
    }
}
```

**Comment by cigrainger** [comment]
> Lazy frames has the option to scan a directory

Ah of course -- I was getting confused with reading into an existing frame. Yes we could absolutely use the lazy reader for the entire directory. And we could return an eager frame from the backend anyway.

**Comment by josevalim** [comment]
@cigrainger With your lazy insight, doesn't it mean we actually don't need this functionality? I could just do this:

```elixir
1..16
|> Task.async_stream(fn index ->
  Req.get!("s3://path-to-bucket/#{index}.parquet").body
end)
|> Stream.map(&DataFrame.lazy().read_parquet/1)
|> DataFrame.concat_rows()
|> DataFrame.collect()
```

> Instead of building dfs that way, we should use [CsvReader::from_path](https://docs.rs/polars/latest/polars/prelude/struct.CsvReader.html#method.from_path)

Do you mean we need to change the Elixir API or the underlying Rust code?

**Comment by cigrainger** [comment]
Precisely we can do the above @josevalim!

And with a directory of local files we could add the ability to use a directory. In eager we can just use the lazy reader on the directory then collect before returning.

**Comment by joshuataylor** [comment]
Yeah, could we detect the glob on `df_read_csv`? Or maybe just make that a lazy feature?

**Comment by josevalim** [comment]
@joshuataylor maybe instead of passing a glob, should we allow it to receive a list of directories? This way you can expand and filter files on Elixir land and pass the list downstream. Whatever Polars is doing for globs, it most likely can do the same for a list of directories.

**Comment by josevalim** [comment]
So I think we can close this. The only question is if we need to support reading multiple files at once OR if reading multiple files is the same as doing multiple lazy reads and concatting them lazily at the end.

**Comment by cigrainger** [comment]
I think in practice it's the same for polars (fairly certain that's what happening, see Ipc implementation [here](https://docs.rs/polars-lazy/0.22.7/src/polars_lazy/frame/ipc.rs.html#54)), but perhaps we should support reading multiple files in the high level API because other backends may have their own way of doing it?

**Comment by rupurt** [comment]
I feel like it's worth supporting glob patterns for reading so that it's easier to work with the hive table format. Many other tools provide the convenience e.g. https://duckdb.org/docs/data/parquet/overview.html#examples
