### ISSUE TITLE
Encoding is inefficient for series

### ISSUE THREAD

**Issue by joshuataylor** [elixir-nx/explorer#279]
In the macro [encode](https://github.com/elixir-nx/explorer/blob/main/native/explorer/src/datatypes.rs#L217) and encode_list, what happens is this:

```
macro_rules! encode {
    ($s:ident, $env:ident, $convert_function:ident, $out_type:ty) => {
        $s.$convert_function()
            .unwrap()
            .into_iter()
            .collect::<Vec<Option<$out_type>>>()
            .encode($env)
    };
}
```
It's called using `encode!(s, env, bool)`

So what happens here is:
1. Use .bool() (a Polars helper function) to get a `BooleanChunked`
2. Unwrap the result, then convert to iter
3. Collect into a vector of booleans, which can be None (for nil)
4. Rustler then iterates over the vec, encoding each value inside:
4a.
```rust
        let term_array: Vec<NIF_TERM> = self.iter().map(|x| x.encode(env).as_c_arg()).collect();
        unsafe { Term::new(env, list::make_list(env.as_c_arg(), &term_array)) }
```
6. It's then returned as a Term.

Instead, we could not collect in step 3, and encode the terms ourselves as a list (quick code below).
```rust
        let list = $s.$convert_function()
            .unwrap()
            .into_iter()
            .map(|x| x.map(|d| d as $ty).encode(env).as_c_arg())
            .collect::<Vec<NIF_TERM>>();
        
        unsafe { Term::new(env, list::make_list(env.as_c_arg(), &list)) }
```

This saves a collection, heap allocation, etc. I've found not having Rustler reiterate or rebuild over a collected list is much faster as it doesn't need to be rebuilt. See also [iterators](https://nnethercote.github.io/perf-book/iterators.html) here for a great explanation why.

When optimising the Snowflake Arrow code, this made a big difference for large collections.

I'd be happy to do a PR for this with some benchmarks if people are happy with this.

**Comment by josevalim** [comment]
A PR is definitely welcome!
