### ISSUE TITLE
[Question] Compression settings support for write_parquet

### ISSUE THREAD

**Issue by sweco-semtne** [elixir-nx/explorer#291]
Hi!
Thanks for a fantastic library.
I'm wondering if the parquet write method supports compression settings?
If the underlying polars library support it that is.

It seems the python wrapper has an api for it?

DataFrame.write_parquet(file: str | Path | BytesIO, *, compression: None | Literal['uncompressed', 'snappy', 'gzip', 'lzo', 'brotli', 'lz4', 'zstd'] | str = 'lz4', compression_level: int | None = None, statistics: bool = False, row_group_size: int | None = None, use_pyarrow: bool = False, **kwargs: Any) → None¶

**Comment by josevalim** [comment]
We most likely just need an option to support it. In that case, a PR is welcome!

**Comment by cigrainger** [comment]
Yep! [Polars supports it](https://docs.rs/polars/latest/polars/prelude/struct.ParquetWriter.html#method.with_compression). A PR is very welcome :).
