### ISSUE TITLE
Rename after pivot_wider and sumarise swap names from column

### ISSUE THREAD

**Issue by sacabuche** [elixir-nx/explorer#310]
After upgrading from 0.1.2 in 0.2.0 I started to get the columns swapped when we rename the columns after a pivot wider and a summarise, I tried to reduce it to only use `summarise` or only `pivot_wider` and this is not happening, it needs to be used together in order to fail.

I think this is the minimal test to reproduce this bug

```elixir
    test "pivote_wider swaping columns" do
      df = DF.new(
        names: ["cou", "adv", "spo", "cou", "adv", "spo"],
        val: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        team: ["A", "A", "A", "B", "B", "B"],
      )

      df2 =
        df
        |> DF.pivot_wider("names", "val")
        |> DF.group_by("team")
        |> DF.summarise(%{"adv" => [:max], "cou" => [:max], "spo" => [:max]})
        |> DF.rename(cou_max: "cou", adv_max: "adv", spo_max: "spo")

      assert Series.to_list(df2["cou"]) == [1.0, 4.0]
      assert Series.to_list(df2["adv"]) == [2.0, 5.0]
      assert Series.to_list(df2["spo"]) == [3.0, 6.0]
    end
```

This is the result from the test
```
  1) test rename/2 pivote_wider swaping columns (Explorer.DataFrameTest)
     test/explorer/data_frame_test.exs:893
     Assertion with == failed
     code:  assert Series.to_list(df2["cou"]) == [1.0, 4.0]
     left:  [2.0, 5.0]
     right: [1.0, 4.0]
     stacktrace:
       test/explorer/data_frame_test.exs:907: (test)

```

I tried to follow all the code, and may be is possible that the clone function on rust is not keeping the order of the columns when we do pivot_wider + summarise, is just a big, big guess.

**Comment by josevalim** [comment]
This is fixed in main. :) I get at the end:

```
#Explorer.DataFrame<
  Polars[2 x 4]
  team string ["A", "B"]
  cou float [1.0, 4.0]
  adv float [2.0, 5.0]
  spo float [3.0, 6.0]
>
```

**Comment by sacabuche** [comment]
@josevalim mine is still falling :(, I compiled using rust nightly 1.65, I tested in a mac A1 and in linux, are you sure that you have pushed all your changes? By the way, than you for your super fast response

**Comment by philss** [comment]
I could reproduce the problem - btw, thanks for the test case! - and it's a bug.
For what I could understand, in some of the steps we end up with different name ordering between Elixir and Polars. I guess it is in the step of summarizing, but it could be in the pivot step.

In any case I sent a fix => https://github.com/elixir-nx/explorer/pull/311 
Now we are using the proper column names to rename, and not its position.

**Comment by sacabuche** [comment]
@philss thanks pals! you are awesome!
