### ISSUE TITLE
Panic on pivot_wider when a non pivoted column contains floats

### ISSUE THREAD

**Issue by sacabuche** [elixir-nx/explorer#312]
While migrating from 0.1.2 to 0.2.0 (on main) `pivot_wider` is panicking when one of the columns has floats

```elixir
    test "no ids, flat column 2" do
      df1 = DF.new(name: ["one"], value: [1.0], vol: [10.0])
      df2 = DF.pivot_wider(df1, "name", "value")

      # It think this should be the result but may be I'm wrong
      assert DF.to_columns(df2, atom_keys: true) == %{
               one: [1.0],
               vol: [10.0]
             }
    end
```

this is the result

```

:ok
thread '<unnamed>' panicked at 'not implemented', /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.23.1/src/datatypes/mod.rs:338:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/panicking.rs:48:5
   3: <polars_core::datatypes::AnyValue as core::hash::Hash>::hash
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: polars_core::frame::groupby::pivot::<impl polars_core::frame::DataFrame>::compute_row_idx
   6: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
   7: rayon_core::registry::WorkerThread::wait_until_cold
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


  1) test pivot_wider/4 no ids, flat column 2 (Explorer.DataFrameTest)
     test/explorer/data_frame_test.exs:1322
     ** (ErlangError) Erlang error: :nif_panicked
     code: df2 = DF.pivot_wider(df1, "name", "value")
     stacktrace:
       (explorer 0.3.0-dev) Explorer.PolarsBackend.Native.df_pivot_wider(%{__struct__: Explorer.PolarsBackend.DataFrame, resource: #Reference<0.2916344416.4218290179.128067>}, ["vol"], "name", "value")
       (explorer 0.3.0-dev) lib/explorer/polars_backend/shared.ex:28: Explorer.PolarsBackend.Shared.apply_dataframe/3
       (explorer 0.3.0-dev) lib/explorer/polars_backend/data_frame.ex:429: Explorer.PolarsBackend.DataFrame.pivot_wider/5
       test/explorer/data_frame_test.exs:1330: (test)
```

Thanks!

**Comment by philss** [comment]
@sacabuche I'm not sure if this is valid - looks like it should be. The problem is that we have an ID column - the `vol` column - that is a float. Polars seems to not accept that.

I'm going to check if there is another way, or if this is a bug. Thanks for the report!

**Comment by philss** [comment]
Oh, sorry. I already wrote the reason :sweat_smile: 

Anyway, I'm checking this.

**Comment by sacabuche** [comment]
@philss I agree that is a weird case, but I think that it should rise an error at least, instead of panicking, well,may be is a nice to have :P

**Comment by philss** [comment]
Yeah. I think we should raise if polars is not willing to support this.
This was a topic of discussion in an issue: https://github.com/pola-rs/polars/issues/295#issuecomment-763032349, so I'm not sure if they want to change.

We could also try to cast the float series to a series of list (of bytes). And then cast back to float. But this would be slightly slower I think.
Anyway, tomorrow I'm going to experiment some ideas and maybe open an issue upstream.

**Comment by josevalim** [comment]
I actually agree with polars here. I think joins on floats is potentially a very bad idea since:

```
Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 0.3 == 0.2 + 0.1
false
```

I would support raising if trying to join on floats.

**Comment by sacabuche** [comment]
Definitely floats should not be ids! I was just lucky (or unlucky) that the version 0.1.1 supported to use floats as ids, and somehow poorly imitate `pivot_wider` to support multiple columns as values. Should I open other ticket to ask to support that? similar to [polars](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.pivot.html#polars-dataframe-pivot) ?

**Comment by philss** [comment]
> Should I open other ticket to ask to support that? similar to [polars](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.pivot.html#polars-dataframe-pivot) ?

You mean, support multiple columns as values?

**Comment by sacabuche** [comment]
> > Should I open other ticket to ask to support that? similar to [polars](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.pivot.html#polars-dataframe-pivot) ?
> 
> You mean, support multiple columns as values?

yes, I mean exactly that

**Comment by philss** [comment]
@sacabuche I think it worth open an issue for discussion. I could see that [dplyr supports it](https://dbplyr.tidyverse.org/reference/pivot_wider.tbl_lazy.html), but I couldn't find examples. So if you can bring examples of how it would look like, would be awesome!
