### ISSUE TITLE
Inspect.Error for Series containing NaN

### ISSUE THREAD

**Issue by manlon** [elixir-nx/explorer#322]
While attempting to load a CSV file `text.csv` containing
```
num
NaN
7
```
at an IEx console, I got an obscure (to me) Inspect.Error:
```
iex(35)> df = Explorer.DataFrame.from_csv!("test.csv")
%Inspect.Error{
  message: "got ArgumentError with message \"argument error\" while inspecting %{__struct__: Explorer.DataFrame, data: %{__struct__: Explorer.PolarsBackend.DataFrame, resource: #Reference<0.2815926603.3503161362.209328>}, dtypes: %{\"num\" => :float}, groups: [], names: [\"num\"]}"
}
```

The CSV reader apparently parsed `NaN` as a float but was not able to `inspect()` the NaN value.

```
iex(39)> Explorer.DataFrame.dtypes(df)
%{"num" => :float}
```

Omitting the NaN value eliminates the error:
```
iex(40)> Explorer.DataFrame.tail(df, 1)
#Explorer.DataFrame<
  Polars[1 x 1]
  num float [7.0]
>
```

**Comment by josevalim** [comment]
The Erlang VM does not support non finite values directly, so when converting a float series to a list, we will need to encode `NaN`, `Infinity` and `-Infinity` as the atoms `[:nan, :infinity, :neg_infinity]`.

**Comment by philss** [comment]
Just to add: I think for this to work we would need a custom pair of encoder/decoder for float lists in our native code. Looks like by default Rustler returns a `BadArg` error for f64/f32 that are `NaN` or `Infinity`.
