### ISSUE TITLE
Error in the accompanying Livebook notebook: function Explorer.Series.slice/2 is undefined or private

### ISSUE THREAD

**Issue by hugobarauna** [elixir-nx/explorer#327]
The accompanying Livebook notebook contains the following piece of text:

````livemd
Which you can pass to `Explorer.Series.slice/2` if you want the sorted values.

```elixir
Series.slice(s, ids)
```
````

But there's no `Explorer.Series.slice/2` function. There's only the `Explorer.Series.slice/3` one.

When one runs the notebook, the following error is shown:

```
** (UndefinedFunctionError) function Explorer.Series.slice/2 is undefined or private. Did you mean:

      * slice/3
```

**Comment by josevalim** [comment]
The notebook is updated to the main branch but it declares Explorer v0.2.0 on top. It is probably best for you to use the notebook from hexdocs.pm instead! Or update Mix.install to use git.

**Comment by hugobarauna** [comment]
My mistake. I imported the notebook from the main branch but was using Explorer v0.2.0.
