### ISSUE TITLE
Multiplying scalar in mutate_with

### ISSUE THREAD

**Issue by joeybellerose** [elixir-nx/explorer#331]
Is it possible to multiply scalars within a `mutate_with`?  

Below is a picture of the issue I'm running into using Explorer 0.3.0.  

I don't have any problems when not multiplying by 60.  

What am I doing wrong here?
![CleanShot 2022-09-02 at 09 11 17](https://user-images.githubusercontent.com/28072958/188153210-a6e8c6bd-62bb-4aef-9bf6-0efdebc31d8c.png)

**Comment by philss** [comment]
Hi @joeybellerose :wave: 

Sorry, this was a mistake: I forgot to add the `multiply` operation :/
Here is a PR fixing that: https://github.com/elixir-nx/explorer/pull/332

Thank you for pointing out :)

**Comment by joeybellerose** [comment]
Thanks so much for the quick turn!
