### ISSUE TITLE
 What is the best way to avoid divide by zero with `Explorer.Series.divide/2`

### ISSUE THREAD

**Issue by nallwhy** [elixir-nx/explorer#333]
I asked this question on elixir forum, but I didn't get the answer.
https://elixirforum.com/t/what-is-the-best-way-to-avoid-divide-by-zero-with-explorer-series-divide-2/49986

I have two `Explorer.Series` and want to divide the first series with the second series containing 0.

```
series0 = Explorer.Series.from_list([1, 2, 3])
series1 = Explorer.Series.from_list([0, 1, 2])

Explorer.Series.divide(series0, series1)
```

Then it throws an error,

```
thread '<unnamed>' panicked at 'attempt to divide by zero', /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/ops/arith.rs:507:1
 ** (ErlangError) Erlang error: :nif_panicked
    (explorer 0.2.0) Explorer.PolarsBackend.Native.s_div(shape: (3,)
Series: '' [i64]
[
        1
        2
        3
], shape: (3,)
Series: '' [i64]
[
        0
        1
        2
])
    (explorer 0.2.0) lib/explorer/polars_backend/shared.ex:17: Explorer.PolarsBackend.Shared.apply_series/3
```

I think `NaN` or `Infinity` is the right result for dividing by zero. But I don’t know how to get that result with `Explorer.Series.divide/2`.

**Comment by philss** [comment]
I trying to understand how we would archive that. But with the implementation this is not possible. We should at least have a better error message, but I agree that returning `:infinity` would be better - and also follow the https://en.wikipedia.org/wiki/IEEE_754#Exception_handling .

For now I would recommend filtering for the series where is not zero (at the right-hand side) and then apply the division. You can do that by creating a dataframe and then filtering it:

```elixir
series0 = Explorer.Series.from_list([1, 2, 3])
series1 = Explorer.Series.from_list([0, 1, 2])

df = Explorer.DataFrame.new(s0: series0, s1: series1)

df1 = Explorer.DataFrame.filter_with(df, &(Explorer.Series.not_equal(&1["s1"], 0)))
df2 = Explorer.DataFrame.mutate_with(df1, &([s2: Explorer.Series.divide(&1["s0"], &1["s1"])]))
```

Then you can pull your "s2" series if you want with `df2["s2"]`.

**Comment by josevalim** [comment]
@philss in Explorer, division of integers always returns an integer, so we can't return infinity. So the exception is the correct result here. If you cast to floats, then you get infinity:

```elixir
iex(9)> s2 = [0.0, 0.0, 0.0] |> Explorer.Series.from_list()
#Explorer.Series<
  float[3]
  [0.0, 0.0, 0.0]
>
iex(10)> Explorer.Series.divide(s1, s2)
#Explorer.Series<
  float[3]
  [infinity, infinity, infinity]
>
```

So my suggestion is to raise a better exception and ship it :D

**Comment by philss** [comment]
@josevalim oooh, perfect! I totally missed that. OK than, I'm going to suggest a casting in the error message.
Thanks! :D

**Comment by philss** [comment]
Actually, after talking, we decided to return a `:float` series in the division, to align the behavior with Elixir. And we should also add two new series functions: `quotient` and `remainder`, to add more flexibility.

**Comment by philss** [comment]
The changes of https://github.com/elixir-nx/explorer/pull/334 are now in the main. So I'm closing this.
Thanks for reporting, @nallwhy!
