### ISSUE TITLE
Explorer.Series.min(left, right)

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/explorer#337]
I'm trying to find minimum between two columns, and was surprised that there is no such function (like Nx.min/2).
```elixir
alias Explorer.DataFrame, as: EDF
alias Explorer.Series, as: ES

EDF.new(a: [1, 2, 3], b: [3, 2, 1])
|> EDF.mutate(df, [c: &ES.min(&1[:a], &1[:b])])
```
Maybe I do not see something and there is a better way to achieve this than filter + join?
```elixir
EDF.join(
  EDF.filter(df, &ES.less_equal(&1[:a], &1[:b])) |> EDF.mutate(min: &(&1[:a])),
  EDF.filter(df, &ES.less_equal(&1[:b], &1[:a])) |> EDF.mutate(min: &(&1[:b])),
  how: :outer
)
```

**Comment by josevalim** [comment]
@petrkozorezov it seems we need to expose the underlying operation from polars, based on min expression here: https://stackoverflow.com/questions/69888178/calculating-rowwise-minimum-of-two-series

**Comment by philss** [comment]
I think we can use the new `Explorer.Series.select/3` to perform this:

```elixir
require Explorer.DataFrame, as: EDF
alias Explorer.Series, as: ES

df = EDF.new(a: [1, 2, 3], b: [3, 2, 1])
EDF.mutate(df, [c: select(a < b, a, b)])
```

**Comment by sasikumar87** [comment]
@philss @josevalim Is there a way to handle `nil` values in comparison?

```elixir
require Explorer.DataFrame, as: EDF
alias Explorer.Series, as: ES

df = EDF.new(a: [1, 2, nil], b: [3, 2, 1])
EDF.mutate(df, [c: select(a < b, a, b)])
```
gives
```
#Explorer.DataFrame<
  Polars[3 x 3]
  a integer [1, 2, nil]
  b integer [3, 2, 1]
  c integer [1, 2, 1]
>
```

I expect any comparison with nil to return nil .

**Comment by philss** [comment]
@sasikumar87 I'm not sure yet how to handle this. But I think you are correct. If predicate is `nil`, we may want to return `nil`. 

For a quick work around, please try the following:

```elixir
EDF.mutate(df, [c: select(is_nil(a) or is_nil(b), select(is_nil(a), a, b), select(a < b, a, b))])
```

**Comment by josevalim** [comment]
Is this a polars behavior? Maybe it is worth bringing this up there?
