### ISSUE TITLE
Random Sorting With Arrange

### ISSUE THREAD

**Issue by joeybellerose** [elixir-nx/explorer#345]
I'm attempting to sort a grouped data frame, but I appear to be getting different sorting results each time I run the code as shown in the two examples below.

I am using Elixir version 1.13.4 and my dependencies are shown below:
```elixir
Mix.install([
  {:explorer, "~> 0.3.1"},
  {:nx, "~> 0.3.0"},
  {:vega_lite, "~> 0.1.6"},
  {:kino_vega_lite, "~> 0.1.3"}
])
```

What am I doing wrong?

Example 1
![CleanShot 2022-09-10 at 10 29 19](https://user-images.githubusercontent.com/28072958/189487898-7918ac09-65cc-4994-90f1-4c7ba1e5b226.png)

Example 2

![CleanShot 2022-09-10 at 10 30 32](https://user-images.githubusercontent.com/28072958/189487944-221d4497-cfe4-441d-9e46-b0eec0a02688.png)

Thanks in advance for the help!

**Comment by philss** [comment]
Hey @joeybellerose 👋

The behavior is fixed in a branch I'm working on.
The sorting is going to be stable inside groups.

I will let you know when it's fixed. :)

**Comment by joeybellerose** [comment]
@philss Thanks so much!

**Comment by philss** [comment]
@joeybellerose Sorry for the delay :grimacing: 

Please check the version of `main`. It is fixed there, and should be available in the next release. Thanks for the report!
