### ISSUE TITLE
Incorrect summarization

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/explorer#358]
```elixir
Mix.install([{:explorer, "0.3.1"}])
```

```elixir
alias Explorer.DataFrame, as: EDF
alias Explorer.Series   , as: ES

df = EDF.new([
  ts: ES.from_list([1, 1, 1, 1, 1]),
  price: ES.from_list([3.3, 3.4, 3.5, 3.6, 3.7]),
  mask: ES.from_list([1, 1, 1, 1, 0]),
])

df
|> EDF.arrange(:price) # without this line everything works as should
|> EDF.group_by(:ts)
|> EDF.summarise_with(&[p: ES.multiply(&1[:price], &1[:mask]) |> ES.max()])
```
Result should be `3.6`, but it's `0.0`
```
#Explorer.DataFrame<
  Polars[1 x 2]
  ts integer [1]
  p float [0.0]
>
```

the same behavior simple `summarise`
```elixir
df
|> EDF.arrange(:price) # without this line everything works as should
|> EDF.mutate_with(&[pp: ES.multiply(&1[:price], &1[:mask])])
|> EDF.group_by(:ts)
|> EDF.summarise([pp: [:max]])
```

**Comment by philss** [comment]
Hi @petrkozorezov :wave: 

I think the problem is that `summarise_with/2` does not know which row to pick inside the group in order to make the multiply operation.
You can use operations like `Series.first/1` or `Series.last/1` to take the right mask inside the group:

```elixir
alias Explorer.DataFrame, as: EDF
alias Explorer.Series   , as: ES

df = EDF.new([
  ts: ES.from_list([1, 1, 1, 1, 1]),
  price: ES.from_list([3.3, 3.4, 3.5, 3.6, 3.7]),
  mask: ES.from_list([1, 1, 1, 1, 0]),
])

df
|> EDF.arrange(:price)
|> EDF.group_by(:ts)
|> EDF.summarise_with(&[p: ES.multiply(&1[:price], ES.first(&1[:mask])) |> ES.max()])
```

But, if I understood correctly, you could add the column with a `mutate_with/2` before groupping and summarising:

```elixir
alias Explorer.DataFrame, as: EDF
alias Explorer.Series   , as: ES

df = EDF.new([
  ts: ES.from_list([1, 1, 1, 1, 1]),
  price: ES.from_list([3.3, 3.4, 3.5, 3.6, 3.7]),
  mask: ES.from_list([1, 1, 1, 1, 0]),
])

df
|> EDF.arrange(:price)
|> EDF.mutate_with(&[p: ES.multiply(&1[:price], &1[:mask])])
|> EDF.group_by(:ts)
|> EDF.summarise_with(&[p_max: ES.max(&1[:p])])
```

Does it makes sense?

**Comment by petrkozorezov** [comment]
This is a minimal working example, my real case is much more complected.
And the another working solution for this problem is to swap `ES.multiply` argument.
But I think this is incorrect and unexpected behavior.
I was surprised to see it after a few hours of debugging.

**Comment by philss** [comment]
@petrkozorezov yeah, you are right. This is a bug.
After some investigation, I found that the problem is in Polars -  (we use Polars as the backend of Explorer).
I opened this issue there: https://github.com/pola-rs/polars/issues/4937

**Comment by petrkozorezov** [comment]
@philss great! Thank you!
I thought about, but didn't know how to check, because it isn't obvious to understand what code exactly is generated and passed to polars.

**Comment by philss** [comment]
The problem was fixed upstream - https://github.com/pola-rs/polars/pull/4943. But we need to upgrade to v0.24.0 of Polars and then try to use the version from GitHub. I added an issue for the first upgrade: #359

**Comment by philss** [comment]
@petrkozorezov this is fixed in the main branch. Thanks for the report!
