### ISSUE TITLE
Improvements to the Inspect protocol implementation

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/explorer#36]
As discussed in the WG meeting, this is a suggestion to use the built-in Elixir functions for doc algebra to build the inspect representation

**Comment by cigrainger** [comment]
For sure. I'd love a PR on this!

**Comment by jurraca** [comment]
Hey, not too familiar with the inspect algebra, but are you looking for improvements to [inspect.ex](https://github.com/elixir-nx/explorer/blob/main/lib/explorer/inspect.ex) ? Seems like it's already using `Inspect.Algebra` functions. 
I'd love to look into this if it's still needed @cigrainger

**Comment by josevalim** [comment]
Yes, this seems to be implemented already. Good find @jurraca!
