### ISSUE TITLE
Missing normalisation for "datetime[ns]" dtype

### ISSUE THREAD

**Issue by xaviRodri** [elixir-nx/explorer#364]
Today I was starting my Explorer journey and I pulled a parquet dataset from "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_{year}-{month}.parquet" (e.g.: year -> 2019, month -> 01).

When importing it using `Explorer.DataFrame.from_parquet/1`, I realised we are missing the match to the "datetime[ns]" dtype in the `PolarsBackend.Shared.normalise_dtype/1` function.

Are we really missing it or maybe we don't want it in here?
For the first option, should be enough adding the following match:
```Elixir
def normalise_dtype("datetime[ns]"), do: :datetime
``` 

Pushing a PR with the change so it can be reviewed.

See the error in the attached photo below (using Livebook 📖 )
<img width="757" alt="image" src="https://user-images.githubusercontent.com/32159908/194717290-4bb64f18-4096-43f1-a782-c72f013bf47e.png">

**Comment by josevalim** [comment]
Closing in favor of the PR (so the discussion is in one place).
