### ISSUE TITLE
Allow operation between Series and LazySeries

### ISSUE THREAD

**Issue by nallwhy** [elixir-nx/explorer#367]
- [x] Series + LazySeries -> LazySeries
- [x] LazySeries + Series -> LazySeries

The code below should work.

```elixir
df = Explorer.DataFrame.new(%{a: [1, 2, 3]})

df
|> Explorer.DataFrame.mutate_with(&%{
  b: Explorer.Series.add(&1[:a], Explorer.Series.from_list([1, 2, 3])),
  c: Explorer.Series.add(Explorer.Series.from_list([1, 2, 3]), &1[:a])
})
```

Reference: https://github.com/pola-rs/polars/pull/4988

**Comment by nallwhy** [comment]
Let me handle this issue

**Comment by nallwhy** [comment]
Hmm.. maybe I misunderstood the reference PR.

For the arithmetic operations, polars do series + expr -> series. right?

I need to check series + expr -> expr, expr + series -> series works first.

**Comment by philss** [comment]
@nallwhy I think you need to transform the series to a literal value expression first. Maybe https://docs.rs/polars/latest/polars/series/struct.Series.html#method.lit does the trick, but I'm not sure.

**Comment by nallwhy** [comment]
@philss Thanks! It works :)
