### ISSUE TITLE
Dataset not loading in production

### ISSUE THREAD

**Issue by wadehenning** [elixir-nx/explorer#396]
`Explorer.Datasets.iris` is working fine in dev.  I am loading the data in `mount()`.  The LiveView throwns a immediate Internal Server Error in production on fly.io: `Failed to load resource: the server responded with a status of 500 ()`.

The deploy logs indicate that the dataset is not loading:
![image](https://user-images.githubusercontent.com/10761087/200131411-bfeb54cf-2f82-4a56-9256-188cf6aee401.png)

```
 {:nx, "~> 0.4.0", override: true},
 {:explorer, "~> 0.3.1"},
```

The rest of my application works fine; this is the only place I am loading data.

**Comment by josevalim** [comment]
The datasets are not available in prod because they would balloon the release size and they are rarely used in production. If you need them, then I recommend adding the relevant sources to your app priv directory and loading yourself. I will improve the docs.

**Comment by wadehenning** [comment]
@josevalim thanks.  That is fair and I thought that might be the case.
