### ISSUE TITLE
`filter/2` function grouping on documentation index

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#419]
When reading through the docs one might see that `DataFrame.filter/2` is not properly grouped in the HexDocs modules section/index. Similar functions are grouped in the `Explorer.DataFrame > Functions: Single Table` section, but not filter/2. Is there a reason to do so?
I believe the function should be inside the "Functions: Single Table" subsection.

**Comment by josevalim** [comment]
Good find, it has been fixed in main!
