### ISSUE TITLE
Decide if dummies should be booleans or integers

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#432]
Currently they are u8, but we should not leak multiple integer representations to Elixir. We can either make them i64 or booleans. Booleans look more natural and use less memory.

**Comment by cigrainger** [comment]
I think booleans are fine. The reason I think most folks return 0/1 is for use with math. Dummies are often used in regression, e.g. as fixed effects and in that case you want to be able to multiply etc. Does Nx have a boolean tensor or is it just u8?

**Comment by josevalim** [comment]
> Does Nx have a boolean tensor or is it just u8?

It is just u8. Which brings another concern: polars keeps booleans in a bitmap, which means we need to allocate tensors when converting a series of booleans to tensors.

The other issue is that u8 (not booleans) and u32 returned by polars eventually leak, for example, take this:

```iex
df = Explorer.DataFrame.new a: ["foo", "bar", "baz"]
dummies = Explorer.DataFrame.dummies(df, "a")
dummies["a_foo"] |> Explorer.Series.subtract(dummies["a_foo"]) |> Explorer.Series.subtract(dummies["a_foo")
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /rustc/d394408fb38c4de61f765a3ed5189d2731a1da91/library/core/src/ops/arith.rs:240:1
```

Which is why it is in our best interest to not keep u8 and u32 around. If it is used for regression and multiplication, it sounds like i64 makes more sense?

**Comment by josevalim** [comment]
We can also have the dtype as an option, so any is fine, we just need to pick one as default and perhaps i64 is the least surprising.

**Comment by josevalim** [comment]
Keeping as i64 for now for consistency with other languages unless @cigrainger prefers booleans. :)
