### ISSUE TITLE
Allow series to be given to both Series.slice and DF.slice

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#434]

**Comment by kimjoaoun** [comment]
The idea is calling `Series.slice` when we send a Series to `DF.slice`?

**Comment by philss** [comment]
I'm not sure how is going to work under the hood, but the idea is to accept a `Series` for the indices param of those functions.
- https://hexdocs.pm/explorer/Explorer.Series.html#slice/2
- https://hexdocs.pm/explorer/Explorer.DataFrame.html#slice/2

There is a native function called `df_slice_by_series` that kind of add half of the functionality (it is used for selecting by ranges today). I believe we could use that function for this functionality. We would need to implement something for series and lazy series though.

**Comment by josevalim** [comment]
In the lazy series case, it may be fine to require the series given as a slice to not be lazy. It depends on what polars support.
