### ISSUE TITLE
Add DF.discard(df, columns) instead of DF.select(df, columns, :drop)

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#437]

**Comment by cigrainger** [comment]
I think that's fine. This comes from the `dplyr` idiom of tidy selection using `-column` w/ select. Keeping the number of verbs small is always a good goal, but I don't think discard hurts.

**Comment by josevalim** [comment]
Yeah, my main concern is that there is no easy of us doing `-` in Elixir, which is quite elegant in R and I feel hiding dropping columns behind `select` is too hidden.

**Comment by josevalim** [comment]
I pushed this and I quite like it:

```diff
-      iex> Explorer.DataFrame.select(df, &String.ends_with?(&1, "_fuel"), :drop)
+      iex> Explorer.DataFrame.discard(df, &String.ends_with?(&1, "_fuel"))
```

Albeit it is a new verb, I think the intent is clearer. :)

**Comment by cigrainger** [comment]
I like it too!
