### ISSUE TITLE
Install process fails with timeout in `livebook`

### ISSUE THREAD

**Issue by sobolevn** [elixir-nx/explorer#45]
<img width="929" alt="Снимок экрана 2021-09-04 в 16 20 34" src="https://user-images.githubusercontent.com/4660275/132095883-22c83d3c-622d-4d55-9d5c-b4312d55a669.png">

This code (inside `livebook`)

```elixir
Mix.install([{:explorer, "~> 0.1.0-dev", github: "amplifiedai/explorer"}])
```

Fails with:

```
* Updating explorer (https://github.com/amplifiedai/explorer.git)
origin/HEAD set to main
* Updating nx (https://github.com/elixir-nx/nx.git - origin/main)

** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "rustler"}, 60000)
    ** (EXIT) time out
    (elixir 1.12.2) lib/gen_server.ex:1024: GenServer.call/3
    (hex 0.20.6) lib/hex/remote_converger.ex:182: Hex.RemoteConverger.verify_package_req/4
    (elixir 1.12.2) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (hex 0.20.6) lib/hex/remote_converger.ex:172: Hex.RemoteConverger.verify_input/2
    (hex 0.20.6) lib/hex/remote_converger.ex:42: Hex.RemoteConverger.converge/2
    (mix 1.12.2) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
    (mix 1.12.2) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
    (mix 1.12.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
```

**Comment by josevalim** [comment]
I cannot reproduce this issue. The Hex registry should do an HTTP request and it seems that is not returning in 60 seconds, so it would point related to your connection. Can you reproduce this issue consistently?

**Comment by josevalim** [comment]
Also, is there anything else written/logged?

**Comment by josevalim** [comment]
Another question, does `Mix.install([{:explorer, "~> 0.1.0-dev", github: "amplifiedai/explorer"}])` inside `iex` work? Or does it also fail?

**Comment by sobolevn** [comment]
Yes, looks like it was on my side. Now it works!

Thanks a lot, @josevalim! 

P.S. I am doing several posts about the whole `elixir-nx` eco-system in https://t.me/opensource_findings I hope it will help you a bit with spreading the word! 👍
