### ISSUE TITLE
Add support for using column names with spaces in `Explorer.Query`

### ISSUE THREAD

**Issue by philss** [elixir-nx/explorer#457]
We could support column names that contain spaces (and maybe other special chars).

Take this dataframe as an example:

```elixir
df =
  Explorer.DataFrame.new([
    %{"total clicks" => 1, "sticky" => false},
    %{"total clicks" => 1, "sticky" => false},
    %{"total clicks" => 2, "sticky" => true},
    %{"total clicks" => 2, "sticky" => true}
  ])
```

If we want to summarise by the "total clicks" column, we could do that by using the `summarise_with/2` function:

```elixir
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise_with(&[mean: Explorer.Series.mean(&1["total clicks"])])
```

But we could support the same selection in the macros that are using the `Explorer.Query`.
One idea is to use the syntax: `:"total clicks"`, creating an atom for that. Example: 

```elixir
# This is not valid today
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(mean: mean(:"total clicks"))
```

Thoughts?

**Comment by josevalim** [comment]
We have three options:

1. Introduce a special macro called `col/1` (mirrorring Ecto)

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(mean: mean(col("total clicks")))
```

with dynamic fields:

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(mean: mean(col(^field)))
```

2. Have a special `df` variable which we can access the data frame columns:

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(mean: mean(df["total clicks"]))
```

with dynamic fields:

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(mean: mean(df[^field]))
```

3. Use `across`:

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(across(c <- ["total clicks"], mean: mean(c)))
```

with dynamic fields:

```
df
|> Explorer.DataFrame.group_by("sticky")
|> Explorer.DataFrame.summarise(across(c <- [^field], mean: mean(c)))
```

Any preferences @hugobarauna, @philss, and @cigrainger?

**Comment by philss** [comment]
I didn't like the second option, with the `df` var. This can bring some confusion if the person is using `df` elsewhere.

Using `across` can bring some flexibility, like we discussed in https://github.com/elixir-nx/explorer/issues/223, but at the same time, for the cases like the example, `col/1` can be easier to get used to. So if we could have `col/1` first, and then `across`, it would cover most of the use cases. WDYT?
