### ISSUE TITLE
Handling column names that contain hyphens

### ISSUE THREAD

**Issue by spencerkent** [elixir-nx/explorer#462]
I have a tab-delimited dataset provided by a third party in which they use hyphens extensively in column names. I thought that I might be able to use macros such as `DataFrame.summarise` on columns like this by providing an atom with double quotes: `:"my-column-name"`, but this isn't being handled by [Query.query](https://github.com/elixir-nx/explorer/blob/d051764a85a9dd9f62bddb6919e500ab8b191d5a/lib/explorer/query.ex#L87), which `DataFrame.summarise` calls. Is there a way to do this (use the nice and compact ergonomics of the macros on columns with hyphenated names)? 

I realize I could rename all the columns to use underscores instead of hyphens, or something like that, but I'd like to keep the original column names if I can, to cut down on the amount of schema translation I have to do between my system and this third-party. 

It appears that `DataFrame.summarise_with` would allow me to use these type of columns, at the expense of more verbose code, but it'd be nice to use a macro.

Any suggestions?

**Comment by philss** [comment]
Unfortunately this can't be made today. But we are discussing a solution for this at https://github.com/elixir-nx/explorer/issues/457
So I'm closing this issue since it's duplicated.

Thanks!

**Comment by spencerkent** [comment]
Great, thanks for the follow-up :)
