### ISSUE TITLE
Is it possible to Read CSVs from URL?

### ISSUE THREAD

**Issue by joeybellerose** [elixir-nx/explorer#463]
I am using Livebook 0.8.0 and `{:explorer, "~> 0.4.0"}` and was trying to read the following csv located at https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv.  

When I try to read the csv in using the `from_csv` function I get the following error:

![CleanShot 2023-01-06 at 09 05 05@2x](https://user-images.githubusercontent.com/28072958/211027877-ee1e335c-31ca-41d1-a184-2fdf4ca96ce2.png)

What am I doing wrong here?

**Comment by josevalim** [comment]
You need to use something else to read the file. The `Req` project can be of help and then you use `read_csv` to read it directly from memory.

**Comment by joeybellerose** [comment]
Roger that.  Thanks for the guidance!

**Comment by joeybellerose** [comment]
After playing around with this I came up with the following code:

![CleanShot 2023-01-07 at 00 10 50@2x](https://user-images.githubusercontent.com/28072958/211132236-0ccc5dd0-9f17-42e5-b18e-80b7487a0f40.png)

Given that your directions were pretty straight forward, would it be possible to add the functionality that if a URL is passed that Explorer would automatically handle this for the user?  I'm asking out of ignorance here.  Thanks in advance for the help.

**Comment by cigrainger** [comment]
It's possible but I think it's best to avoid unnecessary dependencies. What I think would be cool would be to add an example to a notebook as documentation. WDYT?

**Comment by joeybellerose** [comment]
Got it. That makes sense.  

A notebook example sounds like a great idea.  

Would [Reading and Writing Data](https://hexdocs.pm/explorer/exploring_explorer.html#reading-and-writing-data) be a good place?

Where do you think it makes the most sense to add this example?
