### ISSUE TITLE
Consistenly allow :nan, :neg_infinity, and :infinity

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#467]
They should be allowed everywhere regular Elixir values are allowed, such as:

1. [x] `Series.from_list([:nan, 1.0, :infinity])` (#495)
2. [x] `Series.eq(series, :nan)` and similar
3. [x] `Series.fill_missing(series, :infinity)` (note `:nan` is already allowed here) (#484)

**Comment by philss** [comment]
I believe all of them are covered now. Thank you very much, @Jhonatannunessilva ! :smiley:  :purple_heart:
