### ISSUE TITLE
Support for more datatypes

### ISSUE THREAD

**Issue by ahnlabb** [elixir-nx/explorer#468]
When trying to load some of my Parquet encoded data (`Explorer.DataFrame.load_parquet!/1`) that include 16-bit unsigned integers I get an error because of the lack of a function clause matching `Explorer.PolarsBackend.Shared.normalise_dtype("u16")`.

To allow the most basic handling of such data I suppose at the minimum the following definitions would need to be changed:

https://github.com/elixir-nx/explorer/blob/664bf7a2b4b0dbb0c9d13c0cc7c7bc294cfcb9e8/lib/explorer/polars_backend/series.ex#L46-L62

https://github.com/elixir-nx/explorer/blob/664bf7a2b4b0dbb0c9d13c0cc7c7bc294cfcb9e8/lib/explorer/polars_backend/shared.ex#L127-L140

adding e.g.

```elixir
      "u16" -> {:u, 16}
      "u64" -> {:u, 64}
      "i8" -> {:s, 8}
      "i16" -> {:s, 16}
      "f32" -> {:f, 32}
```
and

```elixir
  def normalise_dtype("u16"), do: :integer
  def normalise_dtype("u64"), do: :integer
  def normalise_dtype("i8"), do: :integer
  def normalise_dtype("i16"), do: :integer
  def normalise_dtype("f32"), do: :float
```

respectively. Is the basic import of this data within the scope of the project? Should the columns be transformed into the main supported types on import? Is full support for any of these types within the scope of the project?

**Comment by philss** [comment]
Hi @ahnlabb :wave: 
 
 > Is the basic import of this data within the scope of the project?

Yes, you should be apple to import that kind of data or file.

> Should the columns be transformed into the main supported types on import?

I think so. We want to keep the data types supported at a minimum number. Ideally we would have one datatype
for each type (like i64 for integers only).

> Is full support for any of these types within the scope of the project?

No, because we want to keep easier to maintain with fewer types to support.

I'm going to check if we can prevent that by transforming the types at the loading point.

**Comment by josevalim** [comment]
:+1: for converting those on i64 before yielding back to Explorer. We should probably also trim the list in `normalize_dtype`, as we don't use all of those.
