### ISSUE TITLE
Crash - EXC_BAD_ACCESS (SIGBUS)

### ISSUE THREAD

**Issue by davidtew** [elixir-nx/explorer#472]
I wrote some code running on my laptop which uses Explorer to open a local file, saved as parquet, and then post this to a google spreadsheet.  This is in a local phoenix instance.  (Separately, in local livebook, the parquet file is created and is saved, also periodically.)

A genserver periodically calls the code below, once every 20 mins.  After a few hours of troublefree working, BEAM crashed.  I don't know what to make of the crash report.  Perhaps this is of interest to someone here?

(I am a newbie and not a programmer ... I am hacking to get the job done! )

The following is the only Explorer code in the phoenix app:
```
 def unbounce_leads_fetch_from_parquet(qty) do
    universal_keys = [
      "created",
      "name",
      "phone",
      "email",
      "message"
    ]

    qty = qty || 5
    df_parquet_temp = Explorer.DataFrame.from_parquet!("/Users/User/UnbounceLeads_parquet")

    df_subset =
      DataFrame.head(df_parquet_temp, qty)
      |> DataFrame.select(universal_keys)

    Enum.map(DataFrame.names(df_subset), fn head ->
      Explorer.DataFrame.pull(df_subset, head) |> Explorer.Series.to_list()
    end)

  end
```

[crashreport.txt](https://github.com/elixir-nx/explorer/files/10410942/crashreport.txt)

**Comment by josevalim** [comment]
@davidtew if I had to guess:

1. parquet files are memory mapped
2. the error is related to memory access
3. the error happened deep within Rust: `libexplorer-v0.4.0-nif-2.16-x86_64-apple-darwin.so	       0x11820dc73 std::io::Read::read_to_end::hcefb6c0b54d628cf + 243`

This was a hardware fault leading to a crash. Please let us know if you run or you can reproduce this issue consistently.

**Comment by davidtew** [comment]
Thank you.  From hereon in I shall be writing Elixir code to call from and write to many different spreadsheets, so if there is a likelyhood for this to happen it should manifest itself.

(Perhaps I could in future move to a different pc (linux) to see if the different hardware changes things.)

**Comment by philss** [comment]
@davidtew could you try to update to Explorer `v0.5.0`?
We just released yesterday. Since we had a Polars update, maybe this could be fixed (although I didn't find any issue in their repo).

**Comment by davidtew** [comment]
thanks @philss ... upon your suggestion I've upgraded to v0.5
I will let it run and run, and report if there are any more instances

**Comment by philss** [comment]
@davidtew  did you experience the problem again?

**Comment by davidtew** [comment]
@philss everything is fine with the update to v0.5.0 running constantly, now for one month, being called at 7 minutes intervals by GenServers thrice in different modules. Same hardware.
