### ISSUE TITLE
Getting the value of LazySeries inside mutate_with

### ISSUE THREAD

**Issue by a-alhusaini** [elixir-nx/explorer#474]
Hi! I am trying to set the value of a new column based on another column's value via mutate_with. The code I have at the moment is this:

```elixir
house_df = house_df |> Explorer.DataFrame.mutate_with(fn df -> 
  income = df["median_income"]
  Explorer.Series.less(income, 10) |> IO.inspect()
  cond do
  Series.less(income, 1.51) == true -> 
    [income_category: 1]
   Series.less(income, 3.01) == true ->
    [income_category: 2]
   Series.less(income, 4.51) == true ->
    [income_category: 3]
  Series.less(income, 6.01) == true->
    [income_category: 4]
   Series.less(income, 7.51) == true->
    [income_category: 5]
  true -> 
    [income_category: 99]
  end
end)
```

How would I change this to acheive the desired result?

More specifically, when inspecting the value of `income` I see that it is a LazySeries. I am assuming it is behaving like a stream under the hood. How do I actually run math and add a new column based on the underlying value in this situation?

**Comment by josevalim** [comment]
It is not possible right now. You need to use put/3 and compute it outside of a data frame. We can support cond/if inside mutate/2. :)

**Comment by appdevland** [comment]
Thanks! I'll see how well that goes :)

**Comment by philss** [comment]
Hi @appdevland :wave: 

This is not possible because you cannot access a series value inside `_with` functions, due to the fact that you only have a virtual representation of the series.

One possible way to do it is to use a chain of [`Series.select/3`](https://hexdocs.pm/explorer/Explorer.Series.html#select/3)

```rust
house_df =
  house_df
  |> Explorer.DataFrame.mutate_with(fn df ->
    income = df["median_income"]

    income_category =
      Series.select(
        Series.less(income, 1.51),
        1,
        Series.select(
          Series.less(income, 3.01),
          2,
          Series.select(
            Series.less(income, 4.51),
            3,
            Series.select(
              Series.less(income, 6.01),
              4,
              Series.select(Series.less(income, 7.51), 5, 99)
            )
          )
        )
      )

    [income_category: income_category]
  end)
```

I didn't try it, but it should work.

**Comment by ahacking** [comment]
Would an approach similar to to dplyr vectorised switch (case_when and case_match) work? It appears to be a lazy friendly construct that can also be vectorised.

[vectorised switch](https://dplyr.tidyverse.org/reference/case_match.html)

**Comment by josevalim** [comment]
@ahacking I believe that's equivalent to `select/3` except we could make it easier to write by using macros, correct?

**Comment by ahacking** [comment]
Yes I believe macros could be based on using the nested select approach you have shown.

By the way that particular use of select with a predicate was kind of hidden, I had previously looked for an if_else type construct and didn't find it, but I'm glad it's there!

**Comment by josevalim** [comment]
This will now be tracked here #515.
