### ISSUE TITLE
Pandas-esque `hist` function?

### ISSUE THREAD

**Issue by appdevland** [elixir-nx/explorer#503]
In pandas I can create a dataframe and immediately get a histogram of all its parts with a few lines of code:

```
import pandas as pd
import matplotlib as plt

my_data = pd.read_csv("./my_data.csv")
my_data.hist(bins=30)
plt.show()
```

I played around with VegaLite hoping to get something like this setup. I thought about ideas for adding this as part of the Explorer API but couldn't come up with a satisfactory solution.

What does the community think?

**Comment by josevalim** [comment]
The way to do this for now is [Livebook](https://livebook.dev). You can have an explorer dataframe, click the "Smart cell" button and plot a graph. It also has support for binning (a boolean in latest but it can be an integer in main).
