### ISSUE TITLE
[Suggestion] `DataFrame.to_tensor` function?

### ISSUE THREAD

**Issue by a-alhusaini** [elixir-nx/explorer#511]
When playing around with Scholar/Explorer/Nx I find myself converting my explorer dataframe into an nx tensor in order to feed it into Scholar to train a model.

I end up writing code that looks like this:
```elixir
train_split_names = Explorer.DataFrame.names(train_split)
train_series_split = Explorer.DataFrame.to_series(train_split)

Enum.reduce(train_split_names, train_series_split, fn n, acc ->
  acc = Map.replace!(acc, n, Explorer.Series.fill_missing(acc[n], :mean))
  
  if Explorer.Series.dtype(acc[n]) == :string do
    Map.drop(acc, [n])
  else
    Map.replace!(acc, n, Explorer.Series.to_tensor(acc[n]))
  end
end)
```

I think this should be moved to a `DataFrame.to_tensor` function.

I'd love to know what the community thinks!

**Comment by josevalim** [comment]
Please see this commit that does precisely that: https://github.com/elixir-nx/explorer/commit/6c84747c13c66e0278ffca8cead128b3875697c4 - it requires latest Nx and Explorer.

**Comment by josevalim** [comment]
Ah, and this issue #507 is to help with filling missing.
