### ISSUE TITLE
function Explorer.PolarsBackend.Native.df_load_ndjson/3 is undefined

### ISSUE THREAD

**Issue by ndrluis** [elixir-nx/explorer#519]
![image](https://user-images.githubusercontent.com/1859449/221002730-08cc3b75-9c38-4f32-8779-a1229d6ff862.png)

**Comment by philss** [comment]
Hi @ndrluis :wave: :smiley: 

Are you compiling from source?
Did you got the same error using the latest version? (try `Mix.install([:explorer])` from your `iex` terminal)

**Comment by philss** [comment]
Another question: what is the OSX version that you are using?

**Comment by josevalim** [comment]
Also, can you confirm you are running on Apple Silicon? And which machine (M1/M2) are you running on?

**Comment by philss** [comment]
@ndrluis ah, no problem. I wonder if we could detect this type of problem. I opened this issue to track this https://github.com/philss/rustler_precompiled/issues/52
