### ISSUE TITLE
Improve error when passing a non-integer parameter to Explorer.Series.shift

### ISSUE THREAD

**Issue by blutack** [elixir-nx/explorer#523]
I tried to supply a float rather than an integer to Series.shift (as a result of calculating the necessary value based on dividing some other integers and forgetting to cast back). 

Whilst this was completely self inflicted, it would be great for future users if explorer could be a bit more helpful about the specific issue? I didn't find the resulting traceback to give me a very good clue as to what the problem was unfortunately.

Presumably, the `when is_integer` guard / `do: dtype_error ` could be applied to the offset, similar to how it's done for Series.peaks.

Feel free to let me know if you would like me to supply a pull request - I would imagine the fix would go [here].(https://github.com/elixir-nx/explorer/blob/b43b55eff521a79439cce2b502119aed6293163d/lib/explorer/series.ex#L1055) 

Thanks for all your hard work on explorer, NX and friends - it's a pleasure to work with!

Reproducer:
```elixir
s = 1..5 |> Enum.to_list() |> Explorer.Series.from_list()
shift_value = 2 / 1
Explorer.Series.shift(s, shift_value)
```

```
** (ArgumentError) argument error
    (explorer 0.5.1) Explorer.PolarsBackend.Native.s_shift(#Inspect.Error<
  got FunctionClauseError with message:

      """
      no function clause matching in Explorer.PolarsBackend.Shared.apply_series/3
      """

  while inspecting:

      %{
        __struct__: Explorer.PolarsBackend.Series,
        resource: #Reference<0.3148171820.1236664383.227184>
      }

  Stacktrace:

    (explorer 0.5.1) lib/explorer/polars_backend/shared.ex:22: Explorer.PolarsBackend.Shared.apply_series(%{__struct__: Explorer.PolarsBackend.Series, resource: #Reference<0.3148171820.1236664383.227184>}, [], [])
    (explorer 0.5.1) lib/explorer/polars_backend/series.ex:536: Inspect.Explorer.PolarsBackend.Series.inspect/2
    (elixir 1.14.3) lib/inspect/algebra.ex:341: Inspect.Algebra.to_doc/2
    (elixir 1.14.3) lib/kernel.ex:2254: Kernel.inspect/2
    (elixir 1.14.3) lib/exception.ex:717: anonymous fn/2 in Exception.format_arity/1
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.14.3) lib/exception.ex:717: Exception.format_arity/1
    (elixir 1.14.3) lib/exception.ex:712: Exception.format_mfa/3
```

**Comment by josevalim** [comment]
YEs, a guard would be perfect. PR welcome!

**Comment by blutack** [comment]
Excellent, I have opened https://github.com/elixir-nx/explorer/pull/524 and will close this!
