### ISSUE TITLE
EWM implementation discussion

### ISSUE THREAD

**Issue by sasikumar87** [elixir-nx/explorer#527]
I need the EWM calculations from polars for Series. 
Is it ok to implement them ? Because these looks like a very specific use-case and may not be generic like other functions in Series.

https://github.com/pola-rs/polars/blob/master/polars/polars-core/src/series/ops/ewm.rs

**Comment by philss** [comment]
I'm :+1: for this, but I let's wait for @cigrainger and @josevalim inputs :)

I think it worth to read the initial proposal for the feature in Polars: https://github.com/pola-rs/polars/issues/2148

My only concern is naming: we prefer to not abbreviate function names, but I think it's inevitable in this case.

**Comment by josevalim** [comment]
Supporting those are fine by me! The dplyr version is iterative, which wouldn’t be very efficient, so I am ok with adding those directly!

**Comment by cigrainger** [comment]
Absolutely fine by me!

**Comment by kimjoaoun** [comment]
Can I take this one?

**Comment by philss** [comment]
@kimjoaoun I'm not sure if @sasikumar87 is already working on this :thinking:

**Comment by sasikumar87** [comment]
I've started on this.
