### ISSUE TITLE
Support a 2d tensor on Explorer.DF.new

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#530]
We will give column names as `x1`, `x2`, etc, which someone can rename if desired. Implementation is pretty much:

    {_, cols} = Nx.shape()
    DF.new Enum.map(1..cols, fn i -> {"x#{i}", tensor[[.., i]]} end)

Must raise if the tensor rank is not square.

**Comment by msluszniak** [comment]
Range 0..cols-1
