### ISSUE TITLE
Is sorting stable or not?

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/explorer#536]
There is no information about whether `Series.sort` and `DataFrame.arrange` sorting stable or not. I can just try, but I think it would be better if it was explicitly documented.

**Comment by philss** [comment]
We delegate most of the sorting to Polars, and we use the "stable version" of the functions when available. For example, we always use ["groupy_stable"](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.groupby_stable) and ["distinct_stable"](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.unique_stable) when needed.

I believe that all sorting that does not have a "stable / non-stable" distinction is stable. But would be nice to confirm.
Could you try confirm that? And also, PRs are welcome! (but I can document the behaviour if you want).
