### ISSUE TITLE
Version 0.5.3 fails to compile in Livebook notebooks.

### ISSUE THREAD

**Issue by crkent** [elixir-nx/explorer#539]
Executing

```elixir
Mix.install([{:explorer, "== 0.5.3"}])
```
results in the following compilation error 

```
== Compilation error in file lib/explorer.ex ==
** (File.Error) could not read file "README.md": no such file or directory
    (elixir 1.14.1) lib/file.ex:358: File.read!/1
    lib/explorer.ex:5: (module)
```

I did verify that this error is not present in version 0.5.2.

All the same, congrats on shipping 0.5.3!

**Comment by philss** [comment]
@crkent thank you very much for letting us know! It was my mistake. :/

I'm going to prepare `v0.5.4` and retire `v0.5.3`. I will let you know when it's published.

**Comment by philss** [comment]
@crkent version `0.5.4` was published to Hex.pm. Please take a look.

> All the same, congrats on shipping 0.5.3!

Thank you! :purple_heart:

**Comment by crkent** [comment]
Works now! Thanks! :grin:
