### ISSUE TITLE
Add support for log and exp operations in DF.mutate

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/explorer#548]
Currently, there is no other way to calculate the logarithm or exponent of the DataFrame column than separating it from DataFrame, calculating log/exp and putting it back.

**Comment by msluszniak** [comment]
Sure

```elixir
freq_log = data["frequency"] |> S.to_tensor() |> Nx.log() |> Nx.as_type(:f64)
suction_side_displacement_thickness_log = data["suction_side_displacement_thickness"] |> S.to_tensor() |> Nx.log() |> Nx.as_type(:f64)
data = DF.discard(data, ["frequency", "suction_side_displacement_thickness"])
data = DF.put(data, :frequency_log, freq_log)
data = DF.put(data, :suction_side_displacement_thickness_log, suction_side_displacement_thickness_log)

**Comment by philss** [comment]
I'm working on this :)
Since Polars does not include a "log" function in the Rust lib, I'm implementing this like we did with "pow".
I will ping you when the PR is ready!

**Comment by kimjoaoun** [comment]
Hi @philss is there a reason not to use Polars [Log](https://docs.rs/polars/latest/polars/export/num/trait.Float.html#tymethod.log)? It could be implemented in the same way we did with [`Series.max`](https://github.com/elixir-nx/explorer/blob/970cd99d381ea537139e886fc12ee071e7558987/native/explorer/src/series.rs#L714) and max.

**Comment by philss** [comment]
@kimjoaoun I think that module is made to work with Floats as scalars only, not Series. Although I think there is an implementation of `log` hidden behind a feature flag. I'm investigating.
