### ISSUE TITLE
RFC: Rename functions from_ndjson and load_ndjson

### ISSUE THREAD

**Issue by marinac-dev** [elixir-nx/explorer#555]
Hi 👋🏻  
Foremost, supper grateful for this package! 

Currently, the `from_ndjson` function reads data from an `.ndjson` file, while the `load_ndjson` function reads from an `ndjson string`(?? I'm not sure). However, the function names suggest the opposite behavior, which can be confusing for users of the package (confused me for a minute).

By renaming `from_ndjson` to `load_ndjson`, we can make it clear that the function loads data from an `ndjson` file. Additionally, renaming `load_ndjson` to `read_ndjson` more accurately describes the function's behavior of reading ndjson data from an input source.

Any opinions on this?

**Comment by josevalim** [comment]
We discussed this extensively and a lot of it depends on the background. For example, read_csv would totally mean from disk. But I think other people would expect load and dump to be disk based (I personally do not). Anyway, we are settled on the current API. :)
