### ISSUE TITLE
Clarification / Question: Dataframe.filter AND/OR mask?

### ISSUE THREAD

**Issue by drowzy** [elixir-nx/explorer#56]
I see in the docs that one can filter using a mask:

```elixir
df = Explorer.DataFrame.from_map(%{a: ["a", "b", "c"], b: [1, 2, 3]})
Explorer.DataFrame.filter(df, Explorer.Series.greater(df["b"], 1))

#Explorer.DataFrame<
[rows: 2, columns: 2]
a string ["b", "c"]
b integer [2, 3]
>
```

How does one create an AND/OR mask? I could compute them manually and use a list, but is there a better way?
Sort of what I'm looking for:

```elixir
df = Explorer.DataFrame.from_map(%{a: ["a", "b", "c"], b: [1, 2, 3]})
mask = Explorer.Series.or(Explorer.Series.equal(df["b"], 1), Explorer.Series.equal(df["b"], 3))

Explorer.DataFrame.filter(df, mask)

#Explorer.DataFrame<
[rows: 2, columns: 2]
a string ["b", "c"]
b integer [1, 3]
>
```

**Comment by cigrainger** [comment]
There's not anything built in right now, but I think something like this is a great idea. I _think_ polars has something for this. I'll look into it, but would also be happy to accept a PR. :)

**Comment by drowzy** [comment]
Sure! I'll submit a PR :)
