### ISSUE TITLE
ISO 8601 DateTime format with timezone info can't be parsered

### ISSUE THREAD

**Issue by ray-sh** [elixir-nx/explorer#566]
Sample.csv
name,age,birth 
jack,11,2023-01-31T02:09:43.29Z
tom,2,2023-01-31T02:09:43.29Z

f1 = [{"name",:string},{"age",:integer},{"birth",:datetime}]
{:ok, sample} = DF.from_csv("sample.csv", max_rows: 100, dtypes: f1)

Explorer.DataFrame.table(f1), the datetime is nil from the output
+--------------------------------------------+
| Explorer DataFrame: [rows: 2, columns: 3]  |
+-------------+--------------+---------------+
|    name     |     age      |     birth     |
|  <string>   |  <integer>   |  <datetime>   |
+=============+==============+===============+
| jack     | 11           |               |
+-------------+--------------+---------------+
| tom          | 2            |               |
+-------------+--------------+---------------+

**Comment by josevalim** [comment]
Can you please provide a sample `.csv` file in full. Because if your `sample.csv` is as you specify, then it means all of your column names have spaces in them.

**Comment by ray-sh** [comment]
[sample.csv](https://github.com/elixir-nx/explorer/files/11185463/sample.csv)
When you remove the z from the datetime, then the issue is gone.

**Comment by josevalim** [comment]
In this case can you please do a report on Polars? https://github.com/pola-rs/polars

Other than that, the alternative is to parse it as string, remove the Z, and then cast to `:date`.

**Comment by lkarthee** [comment]
Someone reported it - https://github.com/pola-rs/polars/issues/6886.  

In this comment - https://github.com/pola-rs/polars/issues/6886#issuecomment-1435311157, they have changed the parse_dates to try_parse_dates. 

- some documentation about nuances of parsing dates in 10 minutes to explorer
- align the explorer flag with polars flag as it has some context to it  

This issue will be encountered when exporting data without any additional processing from table with columns which are timestamp without timezone   - as ~U[2022-10-27 04:20:15Z] serialised to 2022-10-27T04:20:15Z . Additional processing the field like NaiveDateTime.to_iso8601 will dump to polars expected format. 

```elixir
df = DF.from_csv!(file_path, opts)
df = DF.put(df, :inserted_at, Explorer.Series.transform(df[:inserted_at], &NaiveDateTime.from_iso8601!/1))
```

**Comment by josevalim** [comment]
Yes, we should document or, even better, make sure we raise a nice error message.
