### ISSUE TITLE
DataFrame.iter_rows method?

### ISSUE THREAD

**Issue by mlineen** [elixir-nx/explorer#569]
For larger dataframes, I've found the pattern below to be significantly faster than waiting for and iterating over the result of `DataFrame.to_rows/1`

Should Explorer implement something like [DataFrame.iter_rows](https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.iter_rows.html#polars-dataframe-iter-rows) with a similar warning?

> Row iteration is not optimal as the underlying data is stored in columnar form

```
{n_rows, _} = Explorer.DataFrame.shape(df)
chunk_size = 1_000

# calculate offsets
Range.new(0, n_rows - 1, chunk_size)
|> Stream.map(fn offset -> Explorer.DataFrame.slice(df, offset, chunk_size) end)
|> Stream.map(&Explorer.DataFrame.to_rows/1)
# process each row
|> Enum.each(&IO.inspect/1)
```

I'm also considering adding `Task.async_stream` into this pipeline for concurrency, which is why I'm not sure if the project would prefer this type of processing not be core to the Explorer module.

**Comment by josevalim** [comment]
I believe we could add a `to_rows_stream`, which chunk size as option. A PR is welcome. We can copy the disclaimer from `to_rows` itself. @cigrainger/@philss any other suggestions on the name?

**Comment by cigrainger** [comment]
@josevalim I like the name. And I think this is a great feature to have. :)
