### ISSUE TITLE
Min not working for datetime[NS]

### ISSUE THREAD

**Issue by Hanspagh** [elixir-nx/explorer#575]
Hi. Thank you for a great lib.

When working with some parquet data with a timestamp of precesion NS `datetime[NS]`, the Series.min fails with a panic error. Looking at the code it looks like we only handle the case where the datetime precision is MS.
[https://github.com/elixir-nx/explorer/blob/bcf150595adedb592e028659f435ba3b169a5e93/native/explorer/src/series.rs#L708](https://github.com/elixir-nx/explorer/blob/bcf150595adedb592e028659f435ba3b169a5e93/native/explorer/src/series.rs#L708)

This is also the case with other aggregation functions such as max, is there are gracefull way to handle both NS,MS

**Comment by philss** [comment]
@Hanspagh I think we should be using https://github.com/elixir-nx/explorer/blob/bcf150595adedb592e028659f435ba3b169a5e93/native/explorer/src/encoding.rs#L171 that can handle different time units. Would you mind to send a PR?

**Comment by Hanspagh** [comment]
I can do this

**Comment by Hanspagh** [comment]
@philss, looking at the code, we seem to not really handle NS anywhere I guess because elixir does not support it.
Would it not be possible to "just" change the match of ` DataType::Datetime(TimeUnit::Microseconds, None)` to be any timeunit?

Or should we handle the encoding of the timestamp when we load the data from parquet to never have NS precession in the first place?

**Comment by philss** [comment]
> Would it not be possible to "just" change the match of  DataType::Datetime(TimeUnit::Microseconds, None) to be any timeunit?

> Or should we handle the encoding of the timestamp when we load the data from parquet to never have NS precession in the first place?

We are truncating to microseconds in that `encode_datetime` function, so we will loose precision when encoding NS datetimes to Elixir, but I think there is no other way. We could, in the future, have an option to raise if we couldn't keep precision.

So yeah, I think for now it's enough to change the match to be any timeunit, and use the `encode_datetime` function.
