### ISSUE TITLE
[idea] Allow pivot_wider on categorical values

### ISSUE THREAD

**Issue by dkuku** [elixir-nx/explorer#585]
In machine learning there is often need for sparse columns created from categorical values. The easiest way to it I found this, but it would be nice to just specify a single column like that and fill the defaults with ones (and maybe the rest with zeros ?)
`Explorer.DataFrame.pivot_wider("g")`
```
DF.new(%{id: [11,12,13], g: ~w/m f m/, gid: [1,1,1]})
|> Explorer.DataFrame.pivot_wider("g", "gid")
|> Explorer.DataFrame.table

+--------------------------------------------+
| Explorer DataFrame: [rows: 3, columns: 3]  |
+--------------+--------------+--------------+
|      id      |      m       |      f       |
|  <integer>   |  <integer>   |  <integer>   |
+==============+==============+==============+
| 11           | 1            |              |
+--------------+--------------+--------------+
| 12           |              | 1            |
+--------------+--------------+--------------+
| 13           | 1            |              |
+--------------+--------------+--------------+

```

**Comment by josevalim** [comment]
It should be possible today. Maybe we just need to relax the checks. Can you give it a try please?

**Comment by dkuku** [comment]
Sorry - I clicked enter to early, I was updating the query but it's not livebook - here it just sends the message.

**Comment by josevalim** [comment]
Sorry, I am confused then. Can you please provide a more complete example?

**Comment by dkuku** [comment]
I'm thinking that when we know that this is a categorical value then we don't need to create another column just to create the ones and zeros.
Explorer.DataFrame.pivot_wider(df, "g") should be enough. Maybe with an option to fill empty values with zeros. I think this is a common usecase when preparing data for further processing.

**Comment by dkuku** [comment]
also instead of having second column as a single value would be an option
`Explorer.DataFrame.pivot_wider(df, "g", 1)`

**Comment by josevalim** [comment]
Let’s go in parts then. :) A PR to support categorical values is welcome. It is probably a small change and adding categories to the list of supports columns. Do you want to give it a try? :)

**Comment by dkuku** [comment]
I may try, I never looked at the code but when it's elixir then I should be fine.

**Comment by josevalim** [comment]
Yes, my assumption is that we only need to change the elixir bits

**Comment by dkuku** [comment]
We just need to align how it should look. I think that creating additional column is not needed here. In other places we also accept either column or scalar value.

**Comment by dkuku** [comment]
I probably won't do much here - when trying to run the tests it requires nightly rust and when I run it with nightly I'm getting:
```
RUST_BACKTRACE=1 mix test                                                                                                                                                   
...............thread '<unnamed>' panicked at 'panic in a function that cannot unwind', library/core/src/panicking.rs:126:5
stack backtrace:
..........................[1]    343905 segmentation fault (core dumped)  RUST_BACKTRACE=1 mix test
```

**Comment by philss** [comment]
@dkuku please use the nightly version from our CI, which is `nightly-2023-02-14`.

**Comment by dkuku** [comment]
it works with this version - thanks, I installed it with asdf.
Also I found the solution to my problem. It's the `dummies` function.
