### ISSUE TITLE
create data frame from records

### ISSUE THREAD

**Issue by dustinfarris** [elixir-nx/explorer#59]
We are trying out explorer in our application to do some last-mile data shaping.

We pull records from the db and it would be nice if DataFrame had a function to ingest those.

Currently doing this:

```ex
data = [%{id: 1, name: "John"}, %{id: 2, name: "Jane"}]

df =
  data
  |> Enum.zip_with(
    fn [{key, _value} | _rest] = zipped_column_enum -> 
      %{key => Enum.map(zipped_column_enum, fn {_key, value} -> value end)} 
    end
  )
  |> Enum.reduce(&Map.merge/2)
  |> Explorer.DataFrame.from_map()
```

**Comment by cigrainger** [comment]
Oh totally, `from_records` or `from_list_of_maps` (the former certainly has a better ring to it) has been on the list and I'm feeling that pain as well in my use of it. Your solution looks good! I'll have a think as to whether I can serialise it and do the conversion rust-side to avoid a couple potentially expensive passes over the array elixir-side. This is one of the challenges with Polars being based on Arrow, which is columnar, vs Elixir records being row-oriented.

**Comment by josevalim** [comment]
I think `from_records` can be a bit misleading because of Erlang records. My suggestion would be to go with `from_list`. It has the benefit we can even change it to support lists of maps, lists of tuples, etc in the future.

**Comment by cigrainger** [comment]
Good point! I like `from_list`. I'm less enamoured with the inverse in `to_list` but I think I can get over it. 😛

**Comment by kimjoaoun** [comment]
@cigrainger can I get this one?

**Comment by cigrainger** [comment]
@kimjoaoun sure! Feel free to have a run at it :).
