### ISSUE TITLE
Query Engine

### ISSUE THREAD

**Issue by andyl** [elixir-nx/explorer#609]
Yesterday Jose gave a [twitch session](https://www.twitch.tv/videos/1839481753) in which he discussed concepts for query engines (see timestamp 33:15).  He talked about the DuckDB query language, Polars-style query, tradeoffs between a custom SQL syntax vs adopting another standard, the possibility of federated search across disparate backends.

It strikes me that [Apache Datafusion](https://arrow.apache.org/datafusion/) might be a good fit for an Explorer query language.  Datafusion seems to work across DataFrames and Postgres/Sqlite stores.  It's a Rust library!

DuckDB has some sort of interop with Datafusion.  [[note1](https://duckdb.org/docs/guides/python/datafusion.html), [note2](https://news.ycombinator.com/item?id=29011174)]

As Jose mentioned, there are many approaches for Explorer Query Engines.  Datafusion seems like it might be a good fit so I thought it would be helpful to post some links here. Very excited for the coming ADBC support!

**Comment by josevalim** [comment]
Hi @andyl! Yes, datafusion came up in #55 and we can keep the discussion there. A big question is how much we want to do in Elixir (with its benefits and control) vs Rust. :)
