### ISSUE TITLE
Add parse datetime from string

### ISSUE THREAD

**Issue by anthony-khong** [elixir-nx/explorer#625]
Hello, a new user of Explorer here! I'm not sure if this is already implemented, please point me to the right direction 🙏 

I would like to be able to parse string columns into datetime columns without having to drop down to Elixir. In particular, I have something like the following in mind:

```elixir
  series = Series.from_list(["2023-01-05 12:34:56", "XYZ", nil])

  assert Series.parse_datetime(series, "%Y-%m-%d %H:%M:%S") |> Series.to_list() ==
           [~N[2023-01-05 12:34:56.000000], nil, nil]

  df =
    DF.new(
      a: ["2023-01-05 12:34:56", nil],
      b: ["2023/30/01 00:11:22", "XYZ"]
    )

  df1 =
    DF.mutate(df,
      c: parse_datetime(a, "%Y-%m-%d %H:%M:%S"),
      d: parse_datetime(b, "%Y/%d/%m %H:%M:%S")
    )

  assert DF.to_columns(df1, atom_keys: true) == %{
           a: ["2023-01-05 12:34:56", nil],
           b: ["2023/30/01 00:11:22", "XYZ"],
           c: [~N[2023-01-05 12:34:56.000000], nil],
           d: [~N[2023-01-30 00:11:22.000000], nil]
         }
```

If this would be useful, I've taken a first stab at implementing it [here](https://github.com/elixir-nx/explorer/compare/main...zero-one-group:explorer:parse-datetime?expand=1).

**Comment by josevalim** [comment]
Looks great to me! I would call it strptime and we can add strftime too.
