### ISSUE TITLE
Support `Series.fill_missing/2` also accepting a fixed scalar fill value

### ISSUE THREAD

**Issue by arpieb** [elixir-nx/explorer#63]
I've got a `DataFrame` loaded with a pile of `nils` and would like to be able set those to a fixed value per the `Series.fill_missing/2` function:

```elixir
df["X10"] |> Series.fill_missing(0.0)
```

Currently that function only accepts atoms referencing internal algorithms and raises an exception when passed a scalar.  Let me know if you need anything else or if I can help in any way.

Thanks!

**Comment by kimjoaoun** [comment]
Hey @cigrainger can I get this one?

**Comment by cigrainger** [comment]
Yes please!
