### ISSUE TITLE
add DataFrame.frequencies/2

### ISSUE THREAD

**Issue by anthony-khong** [elixir-nx/explorer#635]
`Series.frequencies/1` already exists and it is based on [value_counts](https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.value_counts.html), but for exploratory data analysis purposes, it would be nice to have a dataframe version. This does not exist in Polars, but [it does in Pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html).

Given: 

```elixir
require Explorer.DataFrame, as: DF
df = DF.new(a: [1, 1, 1, 2, 3, 3], b: [1, 1, 1, 2, 2, 2], c: [1, 2, 3, 4, 5, 6])
```

instead of writing:

```
df
|> DF.group_by([:a, :b])
|> DF.summarise(count: count(a))
|> DF.arrange(desc: count)
```

it's nicer to write a shorter version of: `DF.frequencies(df, [:a, :b])`.

If this looks okay, I'm happy to create the PR for `DataFrame.frequencies/2`.

**Comment by josevalim** [comment]
Love it! A PR is very welcome. :)
