### ISSUE TITLE
Read the default backend from the app environment

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#65]
As done here: https://github.com/elixir-nx/nx/commit/31b7c924f1f8de35e96271bf0d6972a79fc5f937

**Comment by tylerbarker** [comment]
Is this still up for grabs? The equivalent Nx commit looks pretty straightforward - any gotchas/additional considerations I should keep in mind if I gave this a go?

**Comment by cigrainger** [comment]
Definitely still up for grabs @tylerbarker! And I can't think of any gotchas or additional considerations, nope.

**Comment by tylerbarker** [comment]
Sweet, thanks @cigrainger! I'll find some time over the weekend ✌️
