### ISSUE TITLE
caching rust deps locally

### ISSUE THREAD

**Issue by dustinfarris** [elixir-nx/explorer#67]
Not sure if this is possible, but could you suggest a way to keep from having to recompile polars everytime we update to the latest commit here?

**Comment by dustinfarris** [comment]
@cigrainger was this resolved?

**Comment by cigrainger** [comment]
@dustinfarris precompiled Polars will be available soon. I was closing as I thought @philss answer solved the specific issue -- if that's not right I'm happy to reopen.

**Comment by philss** [comment]
Just to give an update: we are waiting for this PR to get merged (or we publish that work as a separated package): https://github.com/rusterlium/rustler/pull/419

I can ping you here when we have the feature :)

**Comment by dustinfarris** [comment]
> @dustinfarris precompiled Polars will be available soon. I was closing as I thought @philss answer solved the specific issue -- if that's not right I'm happy to reopen.

ok got it thanks for clarifying — i'll keep watching the repo for an update on precompiled.

fyi for anyone else watching this, we went with a slightly different workaround:

```ex
config :explorer, Explorer.PolarsBackend.Native,
  # By default, Polars compiles iniside a build directry in deps/explorer.
  # Fully compiling Polars can take well over 15 minutes. This config moves the
  # location outside of deps, so that Polars does not have to fully re-compile
  # whenever deps is cleaned or re-created.  To force Polars to recompile, just
  # remove _explorer from your project root.
  target_dir: Path.expand("_explorer/build")
```

which has been working fairly well in CI (except when GitHub Actions randomly busts our cache for no reason)
