### ISSUE TITLE
Create DataFrame from Series

### ISSUE THREAD

**Issue by dgreiss** [elixir-nx/explorer#68]
Currently, the only ways to create a DataFrame is from a map or by reading from a csv file. It could be helpful to create a DataFrame from a Series (or a list of Series), while also providing column names. 

Similarly, there's no way to add a Series with the correct length to a DataFrame.

Thanks for considering!

**Comment by cigrainger** [comment]
Having thought about this, you can use `from_map` like:

```elixir
s1 = Series.from_list([1, 2])
s2 = Series.from_list(["a", "b"])

df = DataFrame.from_map(%{col1: s1, col2: s2})
```
I actually think that one covers it.

> Similarly, there's no way to add a Series with the correct length to a DataFrame.

This is the same as in R, taking the df from above:

```elixir
s3 = Series.from_list([1.0, 2.0])

new_df = DataFrame.mutate(df, new_col: s3)
```

**Comment by cigrainger** [comment]
Closing this one as I think it's handled by existing behaviour. Please let me know if you disagree!

**Comment by dgreiss** [comment]
Agreed. Your solution is exactly what I needed.
