### ISSUE TITLE
Provide Column Name in Mismatched Type Error Message

### ISSUE THREAD

**Issue by dgreiss** [elixir-nx/explorer#69]
When `DataFrame.from_map`  throws an error when there is a mismatched type, the error message  does not give the column name where the error was found. This is especially needed when the data is large and not easily printed. For example this does not tell me which column is throwing the error:

```
Explorer.DataFrame.from_map(%{a: [1, 1.0], b: ["a", "b"]})
> * (ArgumentError) Cannot make a series from mismatched types. Type of 1.0 does not match inferred dtype integer.
```

**Comment by cigrainger** [comment]
This is a very good point. That would be very helpful. I'm not sure at first glance what the best way of going at this is. My initial reaction would be either to pass the context down to `Series.from_list/1` or to make `Series.check_types/1` public and check the types in `DataFrame.from_map/1`. But the former seems like an unnecessary complication to the public API and the latter would require checking the types twice.
