### ISSUE TITLE
Move datasets out of priv

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/explorer#82]
Files in priv are copied to build and are made part of the release, while likely very unlikely to be used there.

My suggestion is to move them out of priv. We have two options:

1. Move them to `examples` alongside moving `lib/explorer/datasets.ex` to `examples/fossil_fuel.exs`, etc

2. Move them to `datasets`. If we do this, we need to load them like this:

    ```elixir
    @datasets_dir Path.join(File.cwd!(), "datasets")
    
    def fossil_fuel, do: load(Path.join(@datasets_dir, ...)
    ```

**Comment by cigrainger** [comment]
@josevalim I'm comfortable with either one. You're totally right they're very unlikely to be used as part of the release. In case 1, what's the easiest way to keep using them in doctests? I think that's where they're most important (along with notebook documentation). They do have a purpose for coming along for the ride to end users, which is for learning how the library works.

**Comment by josevalim** [comment]
Option 2 would support them on doctests. :)

**Comment by cigrainger** [comment]
Alright, I'll go with option 2 then. :+1:
