### ISSUE TITLE
Feature request: Capture Stream from write_parquet

### ISSUE THREAD

**Issue by olivermt** [elixir-nx/explorer#83]
Context: Be able to write stream to blob instead of having to roundtrip to disk, to allow for scenarios where you want fewer and bigger files

**Comment by cigrainger** [comment]
What's the benefit here over just holding the dataframe in memory and appending to it until you're ready to write to disk?

**Comment by cigrainger** [comment]
@olivermt I'm a bit unclear on this so going to close for now. If you can clarify a bit more for me I'd be very happy to reopen!
