### ISSUE TITLE
Proposal: Dynamically generate dataset functions at compile time

### ISSUE THREAD

**Issue by Benjamin-Philip** [elixir-nx/explorer#85]
Right now, in order to add a dataset, one needs to:

1.  Add the data in `datasets`
2.  Add a function for that dataset in the `Explorer.Datasets` module.

The Problem with this is that we are essentially writing the same code repeatedly:

```elixir
def fossil_fuels,
    do: @datasets_dir |> Path.join("fossil_fuels.csv") |> DataFrame.read_csv!()
```

```elixir
def wine,
    do: @datasets_dir |> Path.join("wine.csv") |> DataFrame.read_csv!()
```

In essence:

```elixir
def unquote(dataset) do
  @datasets_dir
  |> Path.join(unquote(dataset) <> ".csv")
  |> Dataframe.read_csv!()
end
```

Note: I'm pretty new to macros, and I haven't tested this code..

I feel that this is unnecessary repetition which can easily be automated.

--------------------

I propose that we dynamically generate dataset functions at compile time.

To be more specific, I would automate it like this:

Place the data in `datasets/:name/data.csv`.
Place the docs in `datasets/:name/docs.md`.

Iterate over all dirs in `datasets` and write the above function.

**Comment by josevalim** [comment]
It is fine to repeat code when it is 2 LOC. If that still bothers, you can do:

```elixir
def fossil_fuels, do: read!("fossil_fuels.csv")
```

And the duplication is effectively gone while being clear what is the docs, what is the function name, etc.

For example, what happens if we start removing the duplication and then we want to add specs or doc metadata? Or we want to add some post-processing to one of the datasets?

**Comment by Benjamin-Philip** [comment]
> For example, what happens if we start removing the duplication and then we want to add specs or doc metadata? Or we want to add some post-processing to one of the datasets?

So, my assumption is that all datasets are similar and needs to be managed in the same manner. So, if we want to add specs, they would all have the same spec which would be hardcoded in the generation. In the case of docs, it would be read from the`docs.md` file.

Won't a dataset be processed *before* being added to this repo?

However, I get your point of a special case for one dataset. In this case, I would remove this dataset from the list to iterate and write the dataset function by hand.

> And the duplication is effectively gone

Another solution is writing a private function with the dataset name as parameter to load the file, and then writing each function by hand.

**Comment by josevalim** [comment]
> In the case of docs, it would be read from thedocs.md file.

Docs metadata are Elixir code, so we would need to start parsing the `.md` file and evaluating Elixir code. The point is exactly that if your duplication is 2 LOC, that is mostly declaring stuff with docs, specs, and not really any logic, then attempting to remove the duplication is most likely just adding indirection. For example, everyone expects docs to be in `@doc` file, not really in `.md`, and so on.

**Comment by Benjamin-Philip** [comment]
> Docs metadata are Elixir code, so we would need to start parsing the .md file and evaluating Elixir code. The point is exactly that if your duplication is 2 LOC, that is mostly declaring stuff with docs, specs, and not really any logic, then attempting to remove the duplication is most likely just adding indirection. For example, everyone expects docs to be in the @doc annotation, not really in .md, and so on.

I meant reading the docs.md file at compile time and assigning it to the `@doc` annotation.

> EDIT: to further add to this, I don't think the plan is to have many datasets as part of this repo either, especially as scidata is meant to cover the larger ones.

What do you think of this:

```elixir
def fossil_fuels, do: read_dataset("fossil_fuels")

defp read_dataset(name) do
@datasets_dir
  |> Path.join(name <> ".csv")
  |> Dataframe.read_csv!()
end
```

**Comment by josevalim** [comment]
> I meant reading the docs.md file at compile time and assigning it to the @doc annotation. So:

I understood. What I mean in the context of someone reading the source code later on, they wouldn't expect the docs in a markdown file.

> What do you think of this:

Right, that's pretty much what I had in mind for `read!`. :)

**Comment by Benjamin-Philip** [comment]
> I understood. What I mean in the context of someone reading the source code later on, they wouldn't expect the docs in a markdown file.

Yes that's an issue.

> Right, that's pretty much what I had in mind for read!. :)

Shall I submit a pr then?

**Comment by josevalim** [comment]
It is fine by me. I don't mind the current code but extracting it also works.
