### ISSUE TITLE
compilation succeeded, but the on_load function failed on my macbook pro (Big Sur) with apple M1 chip

### ISSUE THREAD

**Issue by zhangzhen** [elixir-nx/explorer#87]
How can I solve this issue?
Error messages printed on the console where livebook is started:

10:03:43.111 [warn]  The on_load function for module Elixir.Explorer.PolarsBackend.Native returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/zhangzh/Library/Caches/mix/installs/elixir-1.12.3-erts-12.1/c8c0b2eb20455bd67cc55fc3c3acd0de/_build/prod/lib/explorer/priv/native/libexplorer.so, 2): no suitable image found.  Did find:\n\t/Users/zhangzh/Library/Caches/mix/installs/elixir-1.12.3-erts-12.1/c8c0b2eb20455bd67cc55fc3c3acd0de/_build/prod/lib/explorer/priv/native/libexplorer.so: mach-o, but wrong architecture\n\t/Users/zhangzh/Library/Caches/mix/installs/elixir-1.12.3-erts-12.1/c8c0b2eb20455bd67cc55fc3c3acd0de/_build/prod/lib/explorer/priv/native/libexplorer.so: stat() failed with errno=35\''}}

=========

```
➜  ~ file /Users/zhangzh/test/my_app/_build/dev/lib/explorer/priv/native/libexplorer.so
/Users/zhangzh/test/my_app/_build/dev/lib/explorer/priv/native/libexplorer.so: Mach-O 64-bit dynamically linked shared library x86_64
```

elixir: 1.12.3-otp-24
erlang: 24.1
rustc: 1.56.1 (59eed8a2a 2021-11-01)

**Comment by josevalim** [comment]
I assume you are using Apple M1 or similar? The error says that one of the libraries used by Explorer is x86_64, but it doesn't say which one. Given it is dynamically linked, it is most likely a system library. You could try to use `otool` to debug it:

    $ otool -L /Users/zhangzh/test/my_app/_build/dev/lib/explorer/priv/native/libexplorer.so

Also try `otool` with no arguments to see other flags available.

**Comment by zhangzhen** [comment]
@josevalim re-installing rust solved this issue. Apple M1 macbook I'm using was transferred from my old Intel macbook.

**Comment by josevalim** [comment]
Fantastic!
