### ISSUE TITLE
 Compilation error in file lib/mix/tasks/rustler.new.e

### ISSUE THREAD

**Issue by puruzio** [elixir-nx/explorer#88]
Elixir 1.13
Erl.  24
Windows 10 

Mix deps.get succesded, but running `mix phx.server`fails with the following error.

==> rustler

Compiling 7 files (.ex)

== Compilation error in file lib/mix/tasks/rustler.new.ex ==

** (File.Error) could not read file "r:/1.PY/Livebook/explore_df/_build/dev/lib/rustler/priv/templates/basic/.cargo/config": I/O error

    (elixir 1.13.1) lib/file.ex:355: File.read!/1

    lib/mix/tasks/rustler.new.ex:29: anonymous fn/3 in :elixir_compiler_9.__MODULE__/1

    (elixir 1.13.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3

    lib/mix/tasks/rustler.new.ex:26: (module)

could not compile dependency :rustler, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile rustler", update it with "mix deps.update rustler" or clean it with "mix deps.clean rustler"

**Comment by cigrainger** [comment]
Thanks for raising this and sorry for the slow response. I think this is an issue with Rustler rather than Explorer but I don't have a windows machine to try things out. Is that file definitely meant to exist? What's in your _build priv directory?

**Comment by puruzio** [comment]
Is that file definitely meant to exist? 
    The error message seems to suggest so.

What's in your _build priv directory?
  Nothing. It's a blank folder. 

Let me close the issue as it probably is a rustler issue as you said. Thanks!
