### ISSUE TITLE
read_csv does not support gziped csv's

### ISSUE THREAD

**Issue by ricpruss** [elixir-nx/explorer#89]
It is common for large csv's to be compressed. Polars supports compressed csv's and autodecompresses them. Feature request maybe or maybe it was just turn off by mistake?

**Comment by josevalim** [comment]
Can you please investigate? Could it also be a version issue?

**Comment by ricpruss** [comment]
Okay, on investigation it is a optional feature, well in polaris allot of things are optional it seems.
Just adding "decompress", to the the depencies section of [dependencies.polars] in explorer/native/explorer/Cargo.toml fixes it.  I made a local working version!

**Comment by cigrainger** [comment]
@ricpruss that's fantastic! Would you mind opening a PR with that addition? I'm sure others would benefit. :)
